# purchasing/migrations/0001_initial.py
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '__first__'),
        ('crm', '__first__'),
        ('material', '__first__'),
        ('tasks', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(max_length=64, unique=True, verbose_name='申请单号')),
                ('title', models.CharField(max_length=255, verbose_name='申购标题')),
                ('department', models.CharField(blank=True, default='', max_length=128, verbose_name='部门')),
                ('request_type', models.CharField(choices=[('project', '项目采购'), ('inventory', '库存补货'), ('asset', '资产采购')], default='inventory', max_length=20, verbose_name='采购类型')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已审批'), ('partially_ordered', '部分下单'), ('ordered', '已完全下单'), ('closed', '已关闭'), ('rejected', '已驳回')], default='draft', max_length=20, verbose_name='状态')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='预估总额')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='期望到货日期')),
                ('reason', models.TextField(blank=True, default='', verbose_name='申购理由')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='finance.employee', verbose_name='申请人')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='finance.company', verbose_name='公司')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='tasks.project', verbose_name='关联项目')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests_created', to='core.user', verbose_name='创建人')),
            ],
            options={'verbose_name': '采购申请', 'verbose_name_plural': '采购申请', 'db_table': 'purchasing_purchase_request', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='申购数量')),
                ('unit', models.CharField(default='PCS', max_length=16, verbose_name='单位')),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='预估单价')),
                ('estimated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='预估金额')),
                ('description', models.TextField(blank=True, default='', verbose_name='规格说明/用途')),
                ('is_optional', models.BooleanField(default=False, verbose_name='可选采购')),
                ('ordered_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='已下单数量')),
                ('received_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='已入库数量')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_items', to='material.material', verbose_name='物料')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.purchaserequest', verbose_name='所属申请')),
            ],
            options={'verbose_name': '采购申请明细', 'verbose_name_plural': '采购申请明细', 'db_table': 'purchasing_purchase_request_item'},
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=64, unique=True, verbose_name='订单号')),
                ('title', models.CharField(max_length=255, verbose_name='订单标题')),
                ('order_type', models.CharField(choices=[('request', '来自申购单'), ('direct', '直接采购')], default='direct', max_length=20, verbose_name='订单类型')),
                ('payment_type', models.CharField(choices=[('prepaid', '预付款'), ('cod', '货到付款'), ('onthirty', '月结30天'), ('onthirtyend', '月结30天末'), ('onthirtypay', '月结30/60/90天'), ('quarterly', '季度结算')], default='onthirty', max_length=20, verbose_name='付款方式')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='订单总额')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='税额')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='折扣金额')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='实际金额')),
                ('currency', models.CharField(default='CNY', max_length=8, verbose_name='币种')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='下单日期')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='期望交货日期')),
                ('actual_delivery_date', models.DateField(blank=True, null=True, verbose_name='实际交货日期')),
                ('delivery_address', models.TextField(blank=True, default='', verbose_name='交货地址')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('sent', '已发供应商'), ('confirmed', '供应商已确认'), ('partial_shipped', '部分发货'), ('shipped', '已发货'), ('partial_received', '部分入库'), ('received', '已完全入库'), ('invoiced', '已开票'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('signed_file', models.FileField(blank=True, null=True, upload_to='purchasing/orders/', verbose_name='签章文件')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='finance.company', verbose_name='公司')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='crm.contact', verbose_name='供应商联系人')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_created', to='core.user', verbose_name='创建人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='tasks.project', verbose_name='关联项目')),
                ('purchase_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='purchasing.purchaserequest', verbose_name='关联申购单')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='crm.supplier', verbose_name='供应商')),
            ],
            options={'verbose_name': '采购订单', 'verbose_name_plural': '采购订单', 'db_table': 'purchasing_purchase_order', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(blank=True, default='', max_length=255, verbose_name='规格型号')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='订购数量')),
                ('unit', models.CharField(default='PCS', max_length=16, verbose_name='单位')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='含税单价')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='金额')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=13.0, max_digits=5, verbose_name='税率%')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='税额')),
                ('delivered_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='已发货数量')),
                ('received_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='已入库数量')),
                ('description', models.TextField(blank=True, default='', verbose_name='备注')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='material.material', verbose_name='物料')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.purchaseorder', verbose_name='所属订单')),
                ('request_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='purchasing.purchaserequestitem', verbose_name='关联申购明细')),
            ],
            options={'verbose_name': '采购订单明细', 'verbose_name_plural': '采购订单明细', 'db_table': 'purchasing_purchase_order_item'},
        ),
        migrations.CreateModel(
            name='PurchaseReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_no', models.CharField(max_length=64, unique=True, verbose_name='入库单号')),
                ('warehouse', models.CharField(blank=True, default='', max_length=64, verbose_name='仓库')),
                ('receive_date', models.DateField(verbose_name='入库日期')),
                ('status', models.CharField(choices=[('pending', '待入库'), ('partial', '部分入库'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receives', to='finance.company', verbose_name='公司')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receives_created', to='core.user', verbose_name='创建人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receives', to='purchasing.purchaseorder', verbose_name='采购订单')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receives', to='finance.employee', verbose_name='收货人')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receives', to='crm.supplier', verbose_name='供应商')),
            ],
            options={'verbose_name': '采购入库', 'verbose_name_plural': '采购入库', 'db_table': 'purchasing_purchase_receive', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='PurchaseReceiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='入库数量')),
                ('unit', models.CharField(default='PCS', max_length=16, verbose_name='单位')),
                ('qualified_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='合格数量')),
                ('defective_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='不合格数量')),
                ('batch_no', models.CharField(blank=True, default='', max_length=64, verbose_name='批号')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='有效期')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receive_items', to='material.material', verbose_name='物料')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receive_items', to='purchasing.purchaseorderitem', verbose_name='订单明细')),
                ('receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.purchasereceive', verbose_name='所属入库单')),
            ],
            options={'verbose_name': '入库明细', 'verbose_name_plural': '入库明细', 'db_table': 'purchasing_purchase_receive_item'},
        ),
        migrations.AddIndex(model_name='purchaserequest', index=models.Index(fields=['request_no'], name='purchasing__request__idx')),
        migrations.AddIndex(model_name='purchaserequest', index=models.Index(fields=['status', 'company_id'], name='purchasing__status_c_idx')),
        migrations.AddIndex(model_name='purchaseorder', index=models.Index(fields=['order_no'], name='purchasing__order_no_idx')),
        migrations.AddIndex(model_name='purchaseorder', index=models.Index(fields=['status', 'company_id'], name='purchasing__po_status_idx')),
        migrations.AddIndex(model_name='purchasereceive', index=models.Index(fields=['receive_no'], name='purchasing__receive__idx')),
    ]
