# Generated by Django 5.2.13 on 2026-05-06 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='purchasing__order_no_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='purchasing__po_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchasereceive',
            name='purchasing__receive__idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequest',
            name='purchasing__request__idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequest',
            name='purchasing__status_c_idx',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='purchasing.purchaserequest', verbose_name='关联申购单'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='request_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='purchasing.purchaserequestitem', verbose_name='关联申购明细'),
        ),
    ]
