# Generated by Django 5.2.13 on 2026-05-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_fix_on_delete_protect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereceive',
            name='receive_date',
            field=models.DateField(auto_now_add=True, verbose_name='入库日期'),
        ),
    ]
