# Generated by Django 5.2.13 on 2026-05-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_receive_date_auto_now_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='company_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='purchasereceiveitem',
            name='company_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='company_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='所属公司'),
        ),
    ]
