# Generated by Django 4.2.18 on 2026-04-18 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowNodeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='节点名称')),
                ('code', models.CharField(max_length=50, verbose_name='节点代码')),
                ('node_type', models.CharField(choices=[('start', '开始'), ('task', '任务节点'), ('approval', '审批节点'), ('condition', '条件节点'), ('end', '结束')], default='task', max_length=20, verbose_name='节点类型')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('assignee_type', models.CharField(choices=[('user', '指定用户'), ('role', '指定角色'), ('field', '字段值')], default='user', max_length=20, verbose_name=' assignee type')),
                ('assignee_value', models.CharField(blank=True, default='', max_length=200, verbose_name=' assignee value')),
                ('order', models.IntegerField(default=0, verbose_name='顺序')),
                ('timeout_hours', models.IntegerField(default=0, verbose_name='超时时间(小时)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '流程节点模板',
                'verbose_name_plural': '流程节点模板',
                'db_table': 'tasks_flow_node_template',
                'ordering': ['template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FlowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='模板代码')),
                ('type', models.CharField(choices=[('development', '开发流程'), ('approval', '审批流程'), ('custom', '自定义')], default='development', max_length=20, verbose_name='类型')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '流程模板',
                'verbose_name_plural': '流程模板',
                'db_table': 'tasks_flow_template',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='项目代码')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '进行中'), ('completed', '已完成'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'tasks_project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='任务标题')),
                ('code', models.CharField(max_length=50, verbose_name='任务编号')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '紧急')], default='medium', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('pending', '待开始'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.project', verbose_name='所属项目')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_tasks', to=settings.AUTH_USER_MODEL, verbose_name='报告人')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'tasks_task',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TaskStageInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('approved', '已通过'), ('rejected', '已拒绝'), ('skipped', '已跳过')], default='pending', max_length=20, verbose_name='状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_assignments', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('node_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_instances', to='tasks.flownodetemplate', verbose_name='节点模板')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_instances', to='tasks.task', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '任务阶段实例',
                'verbose_name_plural': '任务阶段实例',
                'db_table': 'tasks_task_stage_instance',
                'ordering': ['task', 'node_template__order'],
            },
        ),
        migrations.CreateModel(
            name='StageActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('start', '开始'), ('submit', '提交'), ('approve', '批准'), ('reject', '拒绝'), ('transfer', '转交'), ('comment', '评论')], max_length=20, verbose_name='动作')),
                ('comment', models.TextField(blank=True, default='', verbose_name='评论')),
                ('from_status', models.CharField(blank=True, default='', max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(blank=True, default='', max_length=20, verbose_name='新状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_actions', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('stage_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tasks.taskstageinstance', verbose_name='阶段实例')),
            ],
            options={
                'verbose_name': '阶段活动记录',
                'verbose_name_plural': '阶段活动记录',
                'db_table': 'tasks_stage_activity',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, default='', max_length=50, verbose_name='动作')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_transitions', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('from_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions_from', to='tasks.flownodetemplate', verbose_name='源节点')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='tasks.task', verbose_name='所属任务')),
                ('to_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions_to', to='tasks.flownodetemplate', verbose_name='目标节点')),
            ],
            options={
                'verbose_name': '流程流转记录',
                'verbose_name_plural': '流程流转记录',
                'db_table': 'tasks_flow_transition',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='flownodetemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='tasks.flowtemplate', verbose_name='所属模板'),
        ),
        migrations.AlterUniqueTogether(
            name='flownodetemplate',
            unique_together={('template', 'code')},
        ),
    ]
