# Generated by Django 5.2.13 on 2026-04-20 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFlowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待启动'), ('running', '运行中'), ('completed', '已完成'), ('cancelled', '已取消'), ('suspended', '已暂停')], default='pending', max_length=20, verbose_name='状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='启动时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('current_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_in', to='tasks.flownodetemplate', verbose_name='当前节点')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_flows', to=settings.AUTH_USER_MODEL, verbose_name='启动人')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flow_instance', to='tasks.task', verbose_name='所属任务')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='tasks.flowtemplate', verbose_name='流程模板')),
            ],
            options={
                'verbose_name': '任务流程实例',
                'verbose_name_plural': '任务流程实例',
                'db_table': 'tasks_task_flow_instance',
            },
        ),
    ]
