# Generated by Django 5.2.13 on 2026-04-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_add_task_flow_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0, help_text='项目完成进度，0-100', max_digits=5, verbose_name='进度%'),
        ),
    ]
