# Generated by Django 5.2.13 on 2026-04-24 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_wagerecord_approval_flow_fk'),
        ('tasks', '0003_add_project_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='项目预算金额', max_digits=14, null=True, verbose_name='预算'),
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='finance.company', verbose_name='所属公司'),
        ),
    ]
