# Generated by Django 5.2.13 on 2026-05-06 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0010_add_company_id'),
        ('tasks', '0007_add_project_approval'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='tasks_proj_appr_idx',
        ),
        migrations.AddField(
            model_name='flownodetemplate',
            name='company_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='所属公司ID，用于多租户隔离', null=True, verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='flowtemplate',
            name='company_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='所属公司ID，用于多租户隔离', null=True, verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='flowtransition',
            name='company_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='所属公司ID，用于多租户隔离', null=True, verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='stageactivity',
            name='company_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='所属公司ID，用于多租户隔离', null=True, verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='task',
            name='company_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='所属公司ID，用于多租户隔离（从project继承）', null=True, verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='company_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='所属公司ID，用于多租户隔离', null=True, verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='company_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='所属公司ID，用于多租户隔离', null=True, verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='taskdependency',
            name='company_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='所属公司ID，用于多租户隔离', null=True, verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='taskflowinstance',
            name='company_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='所属公司ID，用于多租户隔离', null=True, verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='taskstageinstance',
            name='company_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='所属公司ID，用于多租户隔离', null=True, verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='project',
            name='approval_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='approvals.approvalflow', verbose_name='立项审批流'),
        ),
    ]
