# Generated by Django 5.2.13 on 2026-05-13 04:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_add_company_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='viewers',
            field=models.ManyToManyField(blank=True, help_text='可查看项目进度的关联人员', related_name='viewable_projects', to=settings.AUTH_USER_MODEL, verbose_name='关联查看人员'),
        ),
    ]
