# Generated by Django 4.2.18 on 2026-04-18 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='公司名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='公司代码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司管理',
                'db_table': 'finance_company',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50, unique=True, verbose_name='发票号')),
                ('type', models.CharField(choices=[('income', '收入发票'), ('expense', '支出发票')], max_length=10, verbose_name='类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='金额')),
                ('status', models.CharField(choices=[('pending', '待开票'), ('issued', '已开票'), ('paid', '已支付'), ('cancelled', '已作废')], default='pending', max_length=20, verbose_name='状态')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='开票日期')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='到期日期')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='finance.company', verbose_name='开票公司')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tasks.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '发票',
                'verbose_name_plural': '发票管理',
                'db_table': 'finance_invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='金额')),
                ('date', models.DateField(verbose_name='日期')),
                ('customer', models.CharField(blank=True, default='', max_length=200, verbose_name='客户')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('attachment', models.CharField(blank=True, default='', max_length=500, verbose_name='附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_incomes', to=settings.AUTH_USER_MODEL, verbose_name='录入人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_incomes', to='tasks.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '收入',
                'verbose_name_plural': '收入管理',
                'db_table': 'finance_income',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='金额')),
                ('expense_type', models.CharField(choices=[('expense', '费用报销'), ('advance', '预付款'), ('deposit', '押金'), ('wage', '工资支出')], default='expense', max_length=20, verbose_name='支出类型')),
                ('date', models.DateField(verbose_name='日期')),
                ('supplier', models.CharField(blank=True, default='', max_length=200, verbose_name='供应商')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('attachment', models.CharField(blank=True, default='', max_length=500, verbose_name='附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_expenses', to=settings.AUTH_USER_MODEL, verbose_name='录入人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_expenses', to='tasks.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '支出',
                'verbose_name_plural': '支出管理',
                'db_table': 'finance_expense',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50, verbose_name='员工姓名')),
                ('bank_card', models.CharField(blank=True, default='', max_length=30, verbose_name='银行卡号')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='基本工资')),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='加班费')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='奖金')),
                ('social_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='社保')),
                ('housing_fund', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='公积金')),
                ('leave_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='请假扣款')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='其他扣款')),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='个税前工资')),
                ('tax', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='个税')),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='实发工资')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(choices=[(1, '1月'), (2, '2月'), (3, '3月'), (4, '4月'), (5, '5月'), (6, '6月'), (7, '7月'), (8, '8月'), (9, '9月'), (10, '10月'), (11, '11月'), (12, '12月')], verbose_name='月份')),
                ('department', models.CharField(blank=True, default='', max_length=50, verbose_name='部门')),
                ('position', models.CharField(blank=True, default='', max_length=50, verbose_name='职位')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '已批准'), ('paid', '已发放')], default='draft', max_length=20, verbose_name='状态')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_wage_records', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wage_records', to='finance.company', verbose_name='公司')),
            ],
            options={
                'verbose_name': '工资单',
                'verbose_name_plural': '工资管理',
                'db_table': 'finance_wage_record',
                'ordering': ['-year', '-month', 'company__name', 'employee_name'],
                'unique_together': {('company', 'employee_name', 'year', 'month')},
            },
        ),
    ]
