# Generated by Django 5.2.13 on 2026-04-19 09:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_add_company_to_income_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_active',
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='联系电话'),
        ),
        migrations.AddField(
            model_name='company',
            name='remark',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('active', '启用'), ('inactive', '停用'), ('pending', '待审核')], default='active', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='支出日期', verbose_name='日期'),
        ),
        migrations.AddField(
            model_name='expense',
            name='note',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='income',
            name='status',
            field=models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(blank=True, help_text='兼容性别名', null=True, verbose_name='日期'),
        ),
    ]
