# Generated by Django 5.2.13 on 2026-04-21 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_add_status_and_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagerecord',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='提成'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='communication_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='通讯补贴'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='employee_loan_repayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='员工借款还款'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='leave_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='请假天数'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='meal_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='餐补'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='other_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='其他应发'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='other_loan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='其他借款'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='position_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='岗位工资'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='sick_leave_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='病假天数'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='sick_leave_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='病假扣款'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='taxable_salary',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='个税前工资'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='total_deduction',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='扣款合计'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='交通补贴'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=datetime.date.today, help_text='支出日期', verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='wagerecord',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='应发合计'),
        ),
        migrations.AlterField(
            model_name='wagerecord',
            name='housing_fund',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='公积金扣款'),
        ),
        migrations.AlterField(
            model_name='wagerecord',
            name='social_insurance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='社保扣款'),
        ),
    ]
