# Generated by Django 5.2.13 on 2026-04-22 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_expand_wagerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='counterparty',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='对方公司'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('special', '增值税专用发票'), ('normal', '普通发票')], default='normal', max_length=10, verbose_name='发票类型'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_credited',
            field=models.BooleanField(default=False, verbose_name='已认证抵扣'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='税额'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='如 6% 填 6', max_digits=5, verbose_name='税率'),
        ),
        migrations.CreateModel(
            name='CompanySocialConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_base', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='社保基数')),
                ('pension_rate_employee', models.DecimalField(decimal_places=2, default=8, max_digits=5, verbose_name='养老保险个人比例%')),
                ('pension_rate_company', models.DecimalField(decimal_places=2, default=16, max_digits=5, verbose_name='养老保险公司比例%')),
                ('medical_rate_employee', models.DecimalField(decimal_places=2, default=2, max_digits=5, verbose_name='医疗保险个人比例%')),
                ('medical_rate_company', models.DecimalField(decimal_places=2, default=6, max_digits=5, verbose_name='医疗保险公司比例%')),
                ('unemployment_rate_employee', models.DecimalField(decimal_places=2, default=0.3, max_digits=5, verbose_name='失业保险个人比例%')),
                ('unemployment_rate_company', models.DecimalField(decimal_places=2, default=0.6, max_digits=5, verbose_name='失业保险公司比例%')),
                ('injury_rate_company', models.DecimalField(decimal_places=2, default=0.4, max_digits=5, verbose_name='工伤保险公司比例%')),
                ('housing_fund_base', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='公积金基数')),
                ('housing_fund_rate_employee', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='公积金个人比例%')),
                ('housing_fund_rate_company', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='公积金公司比例%')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_config', to='finance.company', verbose_name='关联公司')),
            ],
            options={
                'verbose_name': '社保公积金配置',
                'verbose_name_plural': '社保公积金配置',
                'db_table': 'finance_social_config',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='工号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('id_card', models.CharField(blank=True, default='', max_length=18, verbose_name='身份证号')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='手机号')),
                ('bank_card', models.CharField(blank=True, default='', max_length=30, verbose_name='银行卡号')),
                ('bank_name', models.CharField(blank=True, default='', max_length=100, verbose_name='开户银行')),
                ('department', models.CharField(blank=True, default='', max_length=50, verbose_name='部门')),
                ('position', models.CharField(blank=True, default='', max_length=50, verbose_name='职位')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='离职日期')),
                ('status', models.CharField(choices=[('active', '在职'), ('probation', '试用期'), ('intern', '实习'), ('resigned', '已离职')], default='active', max_length=20, verbose_name='状态')),
                ('has_social_insurance', models.BooleanField(default=True, verbose_name='是否购买社保')),
                ('has_housing_fund', models.BooleanField(default=False, verbose_name='是否购买公积金')),
                ('social_insurance_base', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='社保基数')),
                ('housing_fund_base', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='公积金基数')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='finance.company', verbose_name='关联公司')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工信息',
                'db_table': 'finance_employee',
                'ordering': ['code', 'name'],
            },
        ),
    ]
