# Generated by Django 5.2.13 on 2026-04-23 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_alter_approvalflow_flow_type'),
        ('finance', '0005_invoice_counterparty_invoice_invoice_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='approval_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_records', to='approvals.approvalflow', verbose_name='关联审批流'),
        ),
        migrations.AddField(
            model_name='income',
            name='approval_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_records', to='approvals.approvalflow', verbose_name='关联审批流'),
        ),
    ]
