# Generated by Django 5.2.13 on 2026-04-23 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_expense_approval_flow_income_approval_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='紧急联系人'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='紧急联系电话'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wage_records', to='finance.employee', verbose_name='关联员工'),
        ),
    ]
