# Generated by Django 5.2.13 on 2026-04-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
        ('finance', '0007_add_wagerecord_employee_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagerecord',
            name='approval_flow',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='wage_records',
                to='approvals.approvalflow',
                verbose_name='关联审批流'
            ),
        ),
    ]
