# Generated by Django 5.2.13 on 2026-05-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_wage_cumulative_tax'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bankstatement',
            new_name='finance_ban_company_79167d_idx',
            old_name='finance_ban_company_id_d5e36b_idx',
        ),
        migrations.RenameIndex(
            model_name='bankstatement',
            new_name='finance_ban_bank_ac_699169_idx',
            old_name='finance_ban_bank_acc_4a3c91_idx',
        ),
        migrations.RenameIndex(
            model_name='bankstatement',
            new_name='finance_ban_bank_se_84a6eb_idx',
            old_name='finance_ban_bank_ser_7d8e2a_idx',
        ),
        migrations.RenameIndex(
            model_name='bankstatement',
            new_name='finance_ban_import__7f033b_idx',
            old_name='finance_ban_import__0c9f6b_idx',
        ),
        migrations.RemoveField(
            model_name='wagerecord',
            name='cumulative_gross',
        ),
        migrations.RemoveField(
            model_name='wagerecord',
            name='cumulative_housing_fund',
        ),
        migrations.RemoveField(
            model_name='wagerecord',
            name='cumulative_social_insurance',
        ),
        migrations.RemoveField(
            model_name='wagerecord',
            name='cumulative_taxable_income',
        ),
        migrations.RemoveField(
            model_name='wagerecord',
            name='prior_cumulative_tax',
        ),
        migrations.RemoveField(
            model_name='wagerecord',
            name='special_deduction',
        ),
    ]
