# Generated by Django 5.2.13 on 2026-05-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_add_company_id_to_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='counterparty_bank',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='对方开户行'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='counterparty_tax_id',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='对方税号'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_code',
            field=models.CharField(choices=[('ICBC', '工商银行'), ('CMB', '招商银行'), ('CCB', '建设银行'), ('BOC', '中国银行'), ('ABC', '农业银行'), ('COMM', '交通银行'), ('PSBC', '邮储银行'), ('PA', '平安银行'), ('OTHER', '其他')], default='OTHER', max_length=20, verbose_name='银行代码'),
        ),
    ]
