# Generated by Django 5.2.13 on 2026-04-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_wagerecord_cumulative_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='income',
            name='status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='wagerecord',
            name='cumulative_tax',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='累计税额'),
        ),
    ]
