# Generated by Django 5.2.13 on 2026-05-08
# BankStatement 新增字段（CMB v2.0 36列完整解析）
# 由于生产DB已通过SQL直接加列，此迁移使用RunSQL防止重复执行报错

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_bank_statement'),
    ]

    # 用 IF NOT EXISTS 防止重复添加（兼容已通过SQL直接加列的生产DB）
    _ADD_COLUMNS = """
    ALTER TABLE finance_bank_statement ADD COLUMN IF NOT EXISTS transaction_type VARCHAR(100);
    ALTER TABLE finance_bank_statement ADD COLUMN IF NOT EXISTS tx_code VARCHAR(50);
    ALTER TABLE finance_bank_statement ADD COLUMN IF NOT EXISTS value_date DATE;
    ALTER TABLE finance_bank_statement ADD COLUMN IF NOT EXISTS biz_name VARCHAR(200);
    ALTER TABLE finance_bank_statement ADD COLUMN IF NOT EXISTS biz_summary TEXT;
    ALTER TABLE finance_bank_statement ADD COLUMN IF NOT EXISTS other_summary TEXT;
    ALTER TABLE finance_bank_statement ADD COLUMN IF NOT EXISTS ext_summary TEXT;
    ALTER TABLE finance_bank_statement ADD COLUMN IF NOT EXISTS biz_ref VARCHAR(100);
    ALTER TABLE finance_bank_statement ADD COLUMN IF NOT EXISTS process_instance VARCHAR(100);
    ALTER TABLE finance_bank_statement ADD COLUMN IF NOT EXISTS bill_no VARCHAR(100);
    ALTER TABLE finance_bank_statement ADD COLUMN IF NOT EXISTS pay_order VARCHAR(100);
    ALTER TABLE finance_bank_statement ADD COLUMN IF NOT EXISTS internal_id VARCHAR(100);
    ALTER TABLE finance_bank_statement ADD COLUMN IF NOT EXISTS parent_account VARCHAR(50);
    ALTER TABLE finance_bank_statement ADD COLUMN IF NOT EXISTS parent_name VARCHAR(200);
    ALTER TABLE finance_bank_statement ADD COLUMN IF NOT EXISTS info_flag VARCHAR(10);
    ALTER TABLE finance_bank_statement ADD COLUMN IF NOT EXISTS attach_flag VARCHAR(10);
    ALTER TABLE finance_bank_statement ADD COLUMN IF NOT EXISTS reverse_flag VARCHAR(10);
    ALTER TABLE finance_bank_statement ADD COLUMN IF NOT EXISTS counterparty_bank_branch VARCHAR(200);
    ALTER TABLE finance_bank_statement ADD COLUMN IF NOT EXISTS counterparty_bank_code VARCHAR(50);
    ALTER TABLE finance_bank_statement ADD COLUMN IF NOT EXISTS counterparty_bank_addr VARCHAR(200);
    """

    operations = [
        migrations.RunSQL(
            sql=_ADD_COLUMNS,
            reverse_sql="""
            ALTER TABLE finance_bank_statement DROP COLUMN IF EXISTS transaction_type;
            ALTER TABLE finance_bank_statement DROP COLUMN IF EXISTS tx_code;
            ALTER TABLE finance_bank_statement DROP COLUMN IF EXISTS value_date;
            ALTER TABLE finance_bank_statement DROP COLUMN IF EXISTS biz_name;
            ALTER TABLE finance_bank_statement DROP COLUMN IF EXISTS biz_summary;
            ALTER TABLE finance_bank_statement DROP COLUMN IF EXISTS other_summary;
            ALTER TABLE finance_bank_statement DROP COLUMN IF EXISTS ext_summary;
            ALTER TABLE finance_bank_statement DROP COLUMN IF EXISTS biz_ref;
            ALTER TABLE finance_bank_statement DROP COLUMN IF EXISTS process_instance;
            ALTER TABLE finance_bank_statement DROP COLUMN IF EXISTS bill_no;
            ALTER TABLE finance_bank_statement DROP COLUMN IF EXISTS pay_order;
            ALTER TABLE finance_bank_statement DROP COLUMN IF EXISTS internal_id;
            ALTER TABLE finance_bank_statement DROP COLUMN IF EXISTS parent_account;
            ALTER TABLE finance_bank_statement DROP COLUMN IF EXISTS parent_name;
            ALTER TABLE finance_bank_statement DROP COLUMN IF EXISTS info_flag;
            ALTER TABLE finance_bank_statement DROP COLUMN IF EXISTS attach_flag;
            ALTER TABLE finance_bank_statement DROP COLUMN IF EXISTS reverse_flag;
            ALTER TABLE finance_bank_statement DROP COLUMN IF EXISTS counterparty_bank_branch;
            ALTER TABLE finance_bank_statement DROP COLUMN IF EXISTS counterparty_bank_code;
            ALTER TABLE finance_bank_statement DROP COLUMN IF EXISTS counterparty_bank_addr;
            """,
        ),
    ]
