# Generated by Django 5.2.13 on 2026-04-25 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_add_user_company'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wagerecord',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='finance.company', verbose_name='主公司'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='部门(主公司)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='职位(主公司)'),
        ),
        migrations.AlterField(
            model_name='wagerecord',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wage_records', to='finance.employee', verbose_name='关联员工(旧)'),
        ),
        migrations.AlterField(
            model_name='wagerecord',
            name='employee_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='员工姓名'),
        ),
        migrations.AlterUniqueTogether(
            name='wagerecord',
            unique_together={('company', 'employee', 'year', 'month')},
        ),
        migrations.CreateModel(
            name='EmployeeCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, default='', max_length=50, verbose_name='部门')),
                ('position', models.CharField(blank=True, default='', max_length=50, verbose_name='职位')),
                ('is_primary', models.BooleanField(default=False, help_text='每员工只能有一个主职', verbose_name='主职')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='离职日期')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_links', to='finance.company', verbose_name='公司')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_links', to='finance.employee', verbose_name='员工')),
            ],
            options={
                'verbose_name': '员工公司关联',
                'verbose_name_plural': '员工公司关联',
                'db_table': 'finance_employee_company',
                'ordering': ['-is_primary', 'company__name'],
                'unique_together': {('employee', 'company')},
            },
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='employee_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wage_records', to='finance.employeecompany', verbose_name='员工任职记录'),
        ),
    ]
