# Generated by Django 5.2.13 on 2026-04-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_multi_company_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysocialconfig',
            name='unemployment_rate_company',
            field=models.DecimalField(decimal_places=3, default=0.6, max_digits=5, verbose_name='失业保险公司比例%'),
        ),
        migrations.AlterField(
            model_name='companysocialconfig',
            name='unemployment_rate_employee',
            field=models.DecimalField(decimal_places=3, default=0.3, max_digits=5, verbose_name='失业保险个人比例%'),
        ),
    ]
