# Generated by Django 5.2.13 on 2026-05-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_fix_wagerecord_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bank_account',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='银行账号'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='开户银行'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='税务登记号'),
        ),
    ]
