# Generated by Django 5.2.13 on 2026-05-08
# BankStatement 往来款标识字段

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_bank_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='往来_remark',
            field=models.TextField(default='', help_text='往来详细说明，如：借款期限、利率、用途等', verbose_name='往来备注'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='往来_type',
            field=models.CharField(default='', help_text='借款/投资款/社保退款/个人往来/待核查', max_length=50, verbose_name='往来类型'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='往来_verified',
            field=models.BooleanField(default=False, verbose_name='往来已核销'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='is_往来',
            field=models.BooleanField(default=False, verbose_name='是否往来款'),
        ),
    ]
