# Generated by Django 5.2.13 on 2026-05-08 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_bank_statement_extend_fields'),
        ('finance', '0016_bank_statement_往来_fields'),
    ]

    operations = [
    ]
