# Generated by Django 5.2.13 on 2026-05-08 05:09
# 修复：BankStatement扩展字段（attach_flag等）在0011/0016已存在，本迁移只加Invoice新增字段

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_merge_20260508_1156'),
    ]

    operations = [
        # Invoice 新增字段
        migrations.AddField(
            model_name='invoice',
            name='matched_bank_statement',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='matched_invoices',
                to='finance.bankstatement',
                verbose_name='核销银行流水'
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_date',
            field=models.DateField(
                blank=True, null=True,
                verbose_name='实际收/付款日期',
                help_text='银行到账/扣款后自动填入'
            ),
        ),
        # AlterField（重新声明以同步枚举）
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(
                choices=[
                    ('salary', '工资薪酬'), ('social', '社保公积金'),
                    ('office', '办公费用'), ('travel', '差旅费用'),
                    ('communication', '通讯费用'), ('entertainment', '业务招待'),
                    ('marketing', '市场营销'), ('rd', '研发费用'),
                    ('tax', '税费'), ('advance', '预付款'), ('other', '其他')
                ],
                default='other', max_length=20, verbose_name='支出类型'
            ),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', '待收款/待付款'),
                    ('paid', '已完成'),
                    ('cancelled', '已作废')
                ],
                default='pending', max_length=20, verbose_name='状态'
            ),
        ),
    ]
