# Generated by Django 5.2.13 on 2026-05-08 12:49
# 为 Income/Expense 增加银行流水11字段扩展（交易时间/余额/对手账号/对手开户行）
# BankStatement 相关字段已存在于 DB，仅对 income/expense 做迁移

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_add_invoice_payment_fields'),
    ]

    operations = [
        # ── Income 新增4字段 ──────────────────────────────────────────────
        migrations.AddField(
            model_name='income',
            name='transaction_time',
            field=models.TimeField(
                blank=True, help_text='来自银行流水的交易时间', null=True,
                verbose_name='交易时间'
            ),
        ),
        migrations.AddField(
            model_name='income',
            name='balance',
            field=models.DecimalField(
                blank=True, decimal_places=2,
                help_text='银行流水交易后的账户余额',
                max_digits=14, null=True, verbose_name='余额'
            ),
        ),
        migrations.AddField(
            model_name='income',
            name='counterparty_account',
            field=models.CharField(
                blank=True, default='',
                help_text='收(付)方银行账号',
                max_length=50, verbose_name='对手账号'
            ),
        ),
        migrations.AddField(
            model_name='income',
            name='counterparty_bank',
            field=models.CharField(
                blank=True, default='',
                help_text='收(付)方开户行名称',
                max_length=200, verbose_name='对手开户行'
            ),
        ),
        # ── Expense 新增4字段 ─────────────────────────────────────────────
        migrations.AddField(
            model_name='expense',
            name='transaction_time',
            field=models.TimeField(
                blank=True, help_text='来自银行流水的交易时间', null=True,
                verbose_name='交易时间'
            ),
        ),
        migrations.AddField(
            model_name='expense',
            name='balance',
            field=models.DecimalField(
                blank=True, decimal_places=2,
                help_text='银行流水交易后的账户余额',
                max_digits=14, null=True, verbose_name='余额'
            ),
        ),
        migrations.AddField(
            model_name='expense',
            name='counterparty_account',
            field=models.CharField(
                blank=True, default='',
                help_text='收(付)方银行账号',
                max_length=50, verbose_name='对手账号'
            ),
        ),
        migrations.AddField(
            model_name='expense',
            name='counterparty_bank',
            field=models.CharField(
                blank=True, default='',
                help_text='收(付)方开户行名称',
                max_length=200, verbose_name='对手开户行'
            ),
        ),
    ]
