# Generated by Django 5.2.13 on 2026-05-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_add_bank_fields_to_income_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='summary',
            field=models.CharField(blank=True, default='', help_text='银行流水原始摘要/附言', max_length=500, verbose_name='摘要'),
        ),
        migrations.AddField(
            model_name='expense',
            name='transaction_type',
            field=models.CharField(blank=True, default='', help_text='银行流水原始交易类型（如：转账/工资/货款）', max_length=100, verbose_name='交易类型'),
        ),
        migrations.AddField(
            model_name='income',
            name='summary',
            field=models.CharField(blank=True, default='', help_text='银行流水原始摘要/附言', max_length=500, verbose_name='摘要'),
        ),
        migrations.AddField(
            model_name='income',
            name='transaction_type',
            field=models.CharField(blank=True, default='', help_text='银行流水原始交易类型（如：转账/工资/货款）', max_length=100, verbose_name='交易类型'),
        ),
    ]
