# Generated by Django 5.2.13 on 2026-05-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_add_transaction_type_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='attach_flag',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='有否附件'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='bill_no',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='票据号'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='biz_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='业务名称'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='biz_ref',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='业务参考号'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='biz_summary',
            field=models.TextField(blank=True, default='', verbose_name='业务摘要'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='counterparty_bank_addr',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='对方行地址'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='counterparty_bank_branch',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='对方分行名'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='counterparty_bank_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='对方行号'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='ext_summary',
            field=models.TextField(blank=True, default='', verbose_name='扩展摘要'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='info_flag',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='信息标志'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='internal_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='内部编号'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='other_summary',
            field=models.TextField(blank=True, default='', verbose_name='其它摘要'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='parent_account',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='母(子)公司账号'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='parent_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='母(子)公司名称'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='pay_order',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='商务支付订单号'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='process_instance',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='流程实例号'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='reverse_flag',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='冲账标志'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='transaction_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='交易类型'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='tx_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='交易分析码'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='value_date',
            field=models.DateField(blank=True, null=True, verbose_name='起息日'),
        ),
        migrations.AddField(
            model_name='expense',
            name='source',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='往来_remark',
            field=models.TextField(blank=True, default='', help_text='往来详细说明，如：借款期限、利率、用途等', verbose_name='往来备注'),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='往来_type',
            field=models.CharField(blank=True, default='', help_text='借款/投资款/社保退款/个人往来/待核查', max_length=50, verbose_name='往来类型'),
        ),
    ]
