# Generated by Django 5.2.13 on 2026-05-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_add_expense_source_field'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bankstatement',
            new_name='finance_ban_company_79167d_idx',
            old_name='finance_ban_company_id_d5e36b_idx',
        ),
        migrations.RenameIndex(
            model_name='bankstatement',
            new_name='finance_ban_bank_ac_699169_idx',
            old_name='finance_ban_bank_acc_4a3c91_idx',
        ),
        migrations.RenameIndex(
            model_name='bankstatement',
            new_name='finance_ban_bank_se_84a6eb_idx',
            old_name='finance_ban_bank_ser_7d8e2a_idx',
        ),
        migrations.RenameIndex(
            model_name='bankstatement',
            new_name='finance_ban_import__7f033b_idx',
            old_name='finance_ban_import__0c9f6b_idx',
        ),
        migrations.AddField(
            model_name='invoice',
            name='counterparty_bank',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='对方开户行'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='counterparty_tax_id',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='对方税号'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='cumulative_gross',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='累计应发工资'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='cumulative_housing_fund',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='累计公积金'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='cumulative_social_insurance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='累计社保'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='cumulative_taxable_income',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='累计应纳税所得额'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='prior_cumulative_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='上月累计已扣税'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='special_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='专项附加扣除'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_code',
            field=models.CharField(choices=[('ICBC', '工商银行'), ('CMB', '招商银行'), ('CCB', '建设银行'), ('BOC', '中国银行'), ('ABC', '农业银行'), ('COMM', '交通银行'), ('PSBC', '邮储银行'), ('PA', '平安银行'), ('OTHER', '其他')], default='OTHER', max_length=20, verbose_name='银行代码'),
        ),
    ]
