# Generated by Django 5.2.13 on 2026-05-12 09:20
# 添加 WageRecord.calculate_gross_and_tax() 引用的 6 个缺失字段

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_add_expense_source_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagerecord',
            name='cumulative_gross',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='累计应发工资'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='cumulative_housing_fund',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='累计公积金'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='cumulative_social_insurance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='累计社保'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='cumulative_taxable_income',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='累计应纳税所得额'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='prior_cumulative_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='上月累计已扣税'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='special_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='专项附加扣除'),
        ),
    ]
