# Generated by Django 5.2.13 on 2026-05-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_add_missing_wage_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bankstatement',
            new_name='finance_ban_company_79167d_idx',
            old_name='finance_ban_company_id_d5e36b_idx',
        ),
        migrations.RenameIndex(
            model_name='bankstatement',
            new_name='finance_ban_bank_ac_699169_idx',
            old_name='finance_ban_bank_acc_4a3c91_idx',
        ),
        migrations.RenameIndex(
            model_name='bankstatement',
            new_name='finance_ban_bank_se_84a6eb_idx',
            old_name='finance_ban_bank_ser_7d8e2a_idx',
        ),
        migrations.RenameIndex(
            model_name='bankstatement',
            new_name='finance_ban_import__7f033b_idx',
            old_name='finance_ban_import__0c9f6b_idx',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='housing_fund_base',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='social_insurance_base',
        ),
        migrations.AddField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='基本工资'),
        ),
        migrations.AddField(
            model_name='employee',
            name='communication_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='通讯补贴'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_loan_repayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='员工贷款月还款'),
        ),
        migrations.AddField(
            model_name='employee',
            name='housing_fund_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='公积金扣款（个人部分）'),
        ),
        migrations.AddField(
            model_name='employee',
            name='late_deduction_per_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='迟到扣款标准（元/次）'),
        ),
        migrations.AddField(
            model_name='employee',
            name='leave_deduction_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='请假扣款标准（元/天）'),
        ),
        migrations.AddField(
            model_name='employee',
            name='meal_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='餐补'),
        ),
        migrations.AddField(
            model_name='employee',
            name='other_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='其他津贴'),
        ),
        migrations.AddField(
            model_name='employee',
            name='other_fixed_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='其他固定扣款'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='岗位工资'),
        ),
        migrations.AddField(
            model_name='employee',
            name='social_insurance_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='社保扣款（个人部分）'),
        ),
        migrations.AddField(
            model_name='employee',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='交通补贴'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='children_education',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='子女教育'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='continuing_education',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='继续教育'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='elderly_support',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='赡养老人'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='housing_loan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='住房贷款利息'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='housing_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='住房租金'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='infant_care',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='3岁以下婴幼儿照护'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='late_times',
            field=models.IntegerField(default=0, verbose_name='迟到次数'),
        ),
        migrations.AddField(
            model_name='wagerecord',
            name='serious_illness',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='大病医疗'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_code',
            field=models.CharField(choices=[('ICBC', '工商银行'), ('CMB', '招商银行'), ('CCB', '建设银行'), ('BOC', '中国银行'), ('ABC', '农业银行'), ('COMM', '交通银行'), ('PSBC', '邮储银行'), ('PA', '平安银行'), ('OTHER', '其他')], default='OTHER', max_length=20, verbose_name='银行代码'),
        ),
    ]
