# Generated by Django 5.2.13 on 2026-05-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_wage_and_employee_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='支出类型'),
        ),
    ]
