# Generated by Django 5.2.13 on 2026-05-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_bank_expense_type_unconstrained'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='counterparty_bank',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='对方开户行'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='counterparty_tax_id',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='对方税号'),
        ),
    ]
