# Generated by Django 6.0.3 on 2026-05-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_allow_null_notify_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('confirmed', '已确认支出')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='income',
            name='status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('received', '已到账')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
