# Generated by Django 5.2.13 on 2026-05-25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_alter_expense_status_alter_income_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(blank=True, default='', max_length=18, verbose_name='身份证号')),
                ('year_month', models.CharField(max_length=7, verbose_name='费款所属期')),
                ('pension_employee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='企业养老个人')),
                ('pension_company', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='企业养老单位')),
                ('pension_bup_employee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='地补养老个人')),
                ('pension_bup_company', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='地补养老单位')),
                ('medical_employee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='基本医疗个人')),
                ('medical_company', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='基本医疗单位')),
                ('unemployment_employee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='失业个人')),
                ('unemployment_company', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='失业单位')),
                ('injury_company', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='工伤单位')),
                ('birth_company', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='生育单位')),
                ('housing_fund_employee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='公积金个人')),
                ('housing_fund_company', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='公积金单位')),
                ('total_employee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='个人缴合计')),
                ('total_company', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单位缴合计')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='费款总计')),
                ('is_reconciled', models.BooleanField(default=False, verbose_name='已核销')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True, verbose_name='核销时间')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_records', to='finance.company', verbose_name='公司')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_records', to='finance.employee', verbose_name='员工')),
            ],
            options={
                'verbose_name': '社保申报记录',
                'verbose_name_plural': '社保申报记录',
                'db_table': 'finance_social_record',
                'ordering': ['-year_month', 'employee__name'],
                'unique_together': {('employee', 'year_month')},
            },
        ),
    ]