# Generated by Django 5.2.13 on 2026-05-26 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_add_bank_branch_code_addr'),
        ('finance', '0029_alter_invoice_options_income_income_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='supplier_ref',
            field=models.ForeignKey(blank=True, help_text='关联到CRM供应商表，用于标准化名称', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_expenses', to='crm.supplier', verbose_name='关联供应商(CRM)'),
        ),
        migrations.AddField(
            model_name='income',
            name='client_ref',
            field=models.ForeignKey(blank=True, help_text='关联到CRM客户表，用于标准化名称', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_incomes', to='crm.client', verbose_name='关联客户(CRM)'),
        ),
    ]
