# Generated by Django 5.2.13 on 2026-05-26 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_income_client_ref_expense_supplier_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(blank=True, help_text='留空表示全年预算；填写表示月度预算', null=True, verbose_name='月份')),
                ('expense_type', models.CharField(choices=[('salary', '工资薪酬'), ('social', '社保公积金'), ('office', '办公费用'), ('travel', '差旅费用'), ('communication', '通讯费用'), ('entertainment', '业务招待'), ('marketing', '市场营销'), ('rd', '研发费用'), ('tax', '税费'), ('other', '其他')], max_length=30, verbose_name='费用类型')),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='预算金额')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finance.company', verbose_name='公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budgets', to=settings.AUTH_USER_MODEL, verbose_name='录入人')),
            ],
            options={
                'verbose_name': '预算',
                'verbose_name_plural': '预算管理',
                'db_table': 'finance_budget',
                'ordering': ['year', 'company__name', 'expense_type'],
                'unique_together': {('company', 'year', 'month', 'expense_type')},
            },
        ),
    ]
