# Generated by Django 5.2.13 on 2026-05-26 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_budget_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='如 4001-01（一级-二级）', max_length=20, verbose_name='科目编码')),
                ('name', models.CharField(max_length=100, verbose_name='科目名称')),
                ('account_type', models.CharField(choices=[('asset', '资产'), ('liability', '负债'), ('equity', '所有者权益'), ('income', '收入'), ('expense', '费用')], max_length=20, verbose_name='科目类型')),
                ('level', models.IntegerField(default=1, help_text='1=一级科目，2=二级科目', verbose_name='层级')),
                ('is_leaf', models.BooleanField(default=True, verbose_name='是否叶子科目')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('company', models.ForeignKey(blank=True, help_text='空=全局科目，有值=公司级专属科目', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='finance.company', verbose_name='所属公司')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance.account', verbose_name='父科目')),
            ],
            options={
                'verbose_name': '会计科目',
                'verbose_name_plural': '会计科目表',
                'db_table': 'finance_account',
                'ordering': ['sort_order', 'code'],
                'unique_together': {('code', 'company')},
            },
        ),
    ]
