# Generated by Django 5.2.13 on 2026-05-27 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0032_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='income_category',
            field=models.CharField(blank=True, choices=[('main_business', '主营业务收入'), ('other_business', '其他业务收入'), ('non_operating', '营业外收入'), ('internal_transfer', '内部往来'), ('equity', '实收资本')], default='', help_text='收入科目分类：主营业务/其他业务/营业外收入/内部往来/实收资本', max_length=50, verbose_name='收入科目'),
        ),
        migrations.CreateModel(
            name='RelatedPartyLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counterparty', models.CharField(help_text='对方公司名或个人姓名', max_length=200, verbose_name='对方名称')),
                ('counterparty_type', models.CharField(choices=[('company', '公司'), ('personal', '个人')], default='company', max_length=20, verbose_name='对方类型')),
                ('direction', models.CharField(choices=[('lend_out', '借出'), ('lend_in', '借入'), ('repay', '还款')], max_length=20, verbose_name='方向')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='金额')),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='该笔往来当前未还余额', max_digits=14, verbose_name='当前余额')),
                ('transaction_date', models.DateField(verbose_name='发生日期')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('source_type', models.CharField(blank=True, default='', help_text='income / expense', max_length=20, verbose_name='来源表')),
                ('source_id', models.IntegerField(blank=True, null=True, verbose_name='来源记录ID')),
                ('status', models.CharField(choices=[('active', '未结清'), ('settled', '已结清')], default='active', max_length=20, verbose_name='状态')),
                ('group_id', models.CharField(blank=True, default='', help_text='同一组分组的借出-还款记录共享此ID，便于追踪', max_length=50, verbose_name='分组ID')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='finance.company', verbose_name='本公司')),
            ],
            options={
                'verbose_name': '关联方往来',
                'verbose_name_plural': '关联方往来台账',
                'db_table': 'finance_related_party_ledger',
                'ordering': ['company', 'transaction_date', 'id'],
            },
        ),
    ]
