# Generated by Django 5.2.13 on 2026-05-27 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0033_related_party_ledger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialrecord',
            options={'ordering': ['-year_month', 'id_card'], 'verbose_name': '社保申报记录', 'verbose_name_plural': '社保申报记录'},
        ),
        migrations.AlterUniqueTogether(
            name='socialrecord',
            unique_together={('company', 'id_card', 'year_month')},
        ),
        migrations.AlterField(
            model_name='budget',
            name='expense_type',
            field=models.CharField(choices=[('salary', '工资薪酬'), ('main_cost', '主营业务成本'), ('admin_expense', '管理费用'), ('finance_expense', '财务费用'), ('tax', '税费'), ('office', '办公费用'), ('travel', '差旅费用'), ('internal_transfer', '内部往来'), ('agency', '代收代付'), ('other', '其他')], max_length=30, verbose_name='费用类型'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(blank=True, choices=[('salary', '工资薪酬'), ('main_cost', '主营业务成本'), ('admin_expense', '管理费用'), ('finance_expense', '财务费用'), ('tax', '税费'), ('office', '办公费用'), ('travel', '差旅费用'), ('internal_transfer', '内部往来'), ('agency', '代收代付'), ('other', '其他')], default='', help_text='支出类型：工资/主营业务成本/管理费用/财务费用/税费/办公费/差旅/内部往来/代收代付/其他', max_length=50, verbose_name='支出类型'),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_category',
            field=models.CharField(blank=True, choices=[('main_business', '主营业务收入'), ('other_business', '其他业务收入'), ('non_operating', '营业外收入'), ('other_income', '其他收益'), ('investment_income', '投资收益'), ('internal_transfer', '内部往来'), ('equity', '实收资本')], default='', help_text='收入科目分类：主营业务/其他业务/营业外收入/其他收益/投资收益/内部往来/实收资本', max_length=50, verbose_name='收入科目'),
        ),
        migrations.AlterField(
            model_name='socialrecord',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_records', to='finance.employee', verbose_name='员工'),
        ),
    ]
