# Generated by Django 5.2.13 on 2026-05-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0034_adjust_social_record_nullable_and_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialrecord',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='姓名'),
        ),
    ]
