# Generated by Django 5.2.13 on 2026-05-28 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0035_add_name_to_social_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='red_invoice_for',
            field=models.ForeignKey(blank=True, help_text='负数发票冲红的原始发票', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='red_invoices', to='finance.invoice', verbose_name='红冲原发票'),
        ),
    ]
