# Generated by Django 5.2.13 on 2026-05-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0036_add_red_invoice_for_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='credited_period',
            field=models.CharField(blank=True, default='', help_text='如 2026-05（实际抵扣的税款所属期）', max_length=7, verbose_name='认证所属期'),
        ),
    ]
