# Generated by Django 5.2.13 on 2026-05-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0037_add_credited_period_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='attachment',
            field=models.FileField(blank=True, help_text='上传发票扫描件/PDF', null=True, upload_to='invoice_attachments/%Y/%m/', verbose_name='发票附件'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='attachment_name',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='附件名'),
        ),
    ]
