# Generated by Django 5.2.13 on 2026-05-29 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0038_add_attachment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialrecord',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='social_records', to='finance.employee', verbose_name='员工'),
        ),
    ]
