# Generated by Django 5.2.13 on 2026-05-29 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0039_change_socialrecord_employee_to_protect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='finance.company', verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_statements', to='finance.company', verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.company', verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='income',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='finance.company', verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='socialrecord',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='social_records', to='finance.company', verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='wagerecord',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wage_records', to='finance.company', verbose_name='公司'),
        ),
    ]
