# Generated by Django 5.2.13 on 2026-05-29 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0040_alter_bankaccount_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='company',
            field=models.ForeignKey(blank=True, help_text='空=全局科目，有值=公司级专属科目', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='finance.company', verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='finance.bankaccount', verbose_name='银行账户'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='finance.company', verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='companysocialconfig',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='social_config', to='finance.company', verbose_name='关联公司'),
        ),
        migrations.AlterField(
            model_name='employeecompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_links', to='finance.company', verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='employeecompany',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_links', to='finance.employee', verbose_name='员工'),
        ),
        migrations.AlterField(
            model_name='relatedpartyledger',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='finance.company', verbose_name='本公司'),
        ),
    ]
