# Generated by Django 6.0.3 on 2026-06-01 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0042_add_income_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='expense_date',
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date.today, help_text='支出日期', verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('confirmed', '已确认支出'), ('paid', '已付款')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
