# Generated by Django 6.0.3 on 2026-06-02 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_drop_client_extra_fields'),
        ('finance', '0043_remove_expense_expense_date_alter_expense_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='该发票对应的销售/采购合同', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='crm.contract', verbose_name='关联合同'),
        ),
    ]
