# Generated by Django 6.0.3 on 2026-06-02 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0044_add_invoice_contract_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseAmortization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如"2026年办公室租金摊销"', max_length=300, verbose_name='摊销名称')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='摊销总额')),
                ('monthly_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='每月摊销额')),
                ('start_date', models.DateField(help_text='摊销起始日期（每月1号）', verbose_name='开始月份')),
                ('end_date', models.DateField(help_text='摊销结束日期（每月1号）', verbose_name='结束月份')),
                ('total_periods', models.IntegerField(default=12, verbose_name='总期数')),
                ('completed_periods', models.IntegerField(default=0, verbose_name='已完成期数')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='剩余待摊金额')),
                ('status', models.CharField(choices=[('active', '摊销中'), ('completed', '已摊完'), ('paused', '已暂停')], default='active', max_length=20, verbose_name='状态')),
                ('category', models.CharField(blank=True, default='', help_text='如"租金""保险费""许可费"', max_length=100, verbose_name='费用类别')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amortizations', to='finance.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_amortizations', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('expense', models.ForeignKey(blank=True, help_text='可选，关联到原始支出记录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amortizations', to='finance.expense', verbose_name='关联支出')),
            ],
            options={
                'verbose_name': '费用摊销',
                'verbose_name_plural': '费用摊销',
                'db_table': 'finance_expense_amortization',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AmortizationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField(help_text='如2026-01-01表示1月份', verbose_name='摊销期间')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='摊销金额')),
                ('is_generated', models.BooleanField(default=False, help_text='是否已生成对应的支出/凭证记录', verbose_name='是否已生成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('amortization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='finance.expenseamortization', verbose_name='所属摊销')),
            ],
            options={
                'verbose_name': '摊销明细',
                'verbose_name_plural': '摊销明细',
                'db_table': 'finance_amortization_entry',
                'ordering': ['period_date'],
                'unique_together': {('amortization', 'period_date')},
            },
        ),
    ]
