# Generated by Django 6.0.3 on 2026-05-21 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0026_alter_expense_status_alter_income_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='唯一标识，如 income / expense / invoice / employee', max_length=50, unique=True, verbose_name='模块代码')),
                ('label', models.CharField(help_text='用户看到的名称，如"收入管理"', max_length=100, verbose_name='显示名称')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='图标')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '功能模块',
                'verbose_name_plural': '功能模块',
                'db_table': 'permission_registry_module',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如 view / create / edit / delete / approve', max_length=50, verbose_name='权限代码')),
                ('label', models.CharField(help_text='用户看到的名称，如"查看"', max_length=100, verbose_name='显示名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='permission_registry.module')),
            ],
            options={
                'verbose_name': '模块权限',
                'verbose_name_plural': '模块权限',
                'db_table': 'permission_registry_module_permission',
                'ordering': ['module', 'sort_order'],
                'unique_together': {('module', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserCompanyPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='每用户在每公司只有一个主体企业，登录后默认上下文', verbose_name='主体企业')),
                ('can_view', models.BooleanField(default=False, verbose_name='查看')),
                ('can_create', models.BooleanField(default=False, verbose_name='新建')),
                ('can_edit', models.BooleanField(default=False, verbose_name='编辑')),
                ('can_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('can_approve', models.BooleanField(default=False, verbose_name='审批')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='finance.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='permission_registry.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户公司权限',
                'verbose_name_plural': '用户公司权限',
                'db_table': 'core_user_company_permission',
                'indexes': [models.Index(fields=['user', 'company'], name='idx_ucp_user_company'), models.Index(fields=['user', 'module'], name='idx_ucp_user_module'), models.Index(fields=['company', 'module'], name='idx_ucp_company_module')],
                'unique_together': {('user', 'company', 'module')},
            },
        ),
    ]
