# Generated by Django 5.2.13 on 2026-05-02 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0005_alter_project_end_date_alter_project_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='设备编码')),
                ('name', models.CharField(max_length=200, verbose_name='设备名称')),
                ('spec', models.CharField(blank=True, default='', max_length=200, verbose_name='规格型号')),
                ('category', models.CharField(choices=[('network', '网络设备'), ('server', '服务器/存储'), ('monitor', '监控设备'), ('cable', '线缆/配件'), ('cabinet', '机柜/工具')], max_length=20, verbose_name='分类')),
                ('management_type', models.CharField(choices=[('serial', '序列号管理'), ('batch', '批次管理'), ('quantity', '数量管理')], max_length=20, verbose_name='管理方式')),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='批次号')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='序列号')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='单位')),
                ('status', models.CharField(choices=[('idle', '闲置'), ('in_use', '使用中'), ('repair', '维修中'), ('scrapped', '报废')], default='idle', max_length=20, verbose_name='状态')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='存放地点')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='采购日期')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='采购价格')),
                ('warranty_end', models.DateField(blank=True, null=True, verbose_name='保修截止日期')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='tasks.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'db_table': 'equipment_equipment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentRepairLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_date', models.DateField(verbose_name='维修日期')),
                ('description', models.TextField(verbose_name='故障描述')),
                ('result', models.TextField(blank=True, default='', verbose_name='维修结果')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='维修费用')),
                ('repair_company', models.CharField(blank=True, default='', max_length=200, verbose_name='维修单位')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_logs', to='equipment.equipment', verbose_name='设备')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_repairs', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
            ],
            options={
                'verbose_name': '维修记录',
                'verbose_name_plural': '维修记录',
                'db_table': 'equipment_repair_log',
                'ordering': ['-repair_date'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('borrow', '领用'), ('return', '归还')], max_length=20, verbose_name='操作类型')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('purpose', models.CharField(blank=True, default='', max_length=500, verbose_name='用途')),
                ('operated_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='备注')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='equipment.equipment', verbose_name='设备')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_operations', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '使用记录',
                'verbose_name_plural': '使用记录',
                'db_table': 'equipment_usage_log',
                'ordering': ['-operated_at'],
            },
        ),
    ]
