# Generated by Django 6.0.3 on 2026-05-04 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='BOM名称')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='版本号')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否当前版本')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_equipment_boms', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('equipment', models.ForeignKey(help_text='选择要建立BOM结构的设备', on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='equipment.equipment', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备BOM',
                'verbose_name_plural': '设备BOM清单',
                'db_table': 'equipment_bom',
                'ordering': ['-created_at'],
                'unique_together': {('equipment', 'version')},
            },
        ),
        migrations.CreateModel(
            name='EquipmentBOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=12, verbose_name='数量')),
                ('unit', models.CharField(default='个', max_length=20, verbose_name='单位')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='排序序号')),
                ('remark', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='equipment.equipmentbom', verbose_name='所属BOM')),
                ('child_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_boms', to='equipment.equipment', verbose_name='子件设备')),
            ],
            options={
                'verbose_name': '设备BOM子件',
                'verbose_name_plural': '设备BOM子件明细',
                'db_table': 'equipment_bom_item',
                'ordering': ['sequence', 'id'],
            },
        ),
    ]
