# Generated by Django 4.2.30 on 2026-05-05 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_remove_bom_add_relation'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentBOMRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=12, verbose_name='数量')),
                ('remark', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_relations', to='equipment.equipment', verbose_name='设备')),
                ('material_bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_relations', to='material.materialbom', verbose_name='物料BOM')),
            ],
            options={
                'verbose_name': '设备BOM关联',
                'verbose_name_plural': '设备BOM关联',
                'db_table': 'equipment_bom_relation',
                'ordering': ['-created_at'],
                'unique_together': {('equipment', 'material_bom')},
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='boms',
            field=models.ManyToManyField(blank=True, related_name='equipments', through='equipment.EquipmentBOMRelation', to='material.materialbom'),
        ),
    ]
