# Generated by Django 5.2.13 on 2026-05-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_remove_bom_add_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='company_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='equipmentbomrelation',
            name='company_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='equipmentrepairlog',
            name='company_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='equipmentusagelog',
            name='company_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='所属公司'),
        ),
    ]
