# Generated by Django 5.2.13 on 2026-05-02 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0004_add_contract_counterparty'),
        ('tasks', '0005_alter_project_end_date_alter_project_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='物料编码')),
                ('name', models.CharField(max_length=200, verbose_name='物料名称')),
                ('spec', models.CharField(blank=True, default='', max_length=200, verbose_name='规格型号')),
                ('category', models.CharField(choices=[('cable', '线缆类'), ('network', '网络设备'), ('server', '服务器/存储'), ('cabinet', '机柜/配件'), ('monitor', '监控设备'), ('access', '门禁设备'), ('software', '软件/许可'), ('tool', '工具/耗材')], max_length=20, verbose_name='分类')),
                ('unit', models.CharField(default='个', max_length=20, verbose_name='单位')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='当前库存')),
                ('alert_threshold', models.PositiveIntegerField(default=10, verbose_name='预警阈值')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='单价')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_materials', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='tasks.project', verbose_name='关联项目')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='crm.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '物料',
                'verbose_name_plural': '物料',
                'db_table': 'material_material',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='使用数量')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='使用时间')),
                ('remark', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='material.material', verbose_name='物料')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_usage_logs', to='tasks.project', verbose_name='使用项目')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='领用人')),
            ],
            options={
                'verbose_name': '物料使用记录',
                'verbose_name_plural': '物料使用记录',
                'db_table': 'material_usage_log',
                'ordering': ['-used_at'],
            },
        ),
    ]
