# Generated by Django 5.2.13 on 2026-05-02 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('remark', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '物料分类',
                'verbose_name_plural': '物料分类',
                'db_table': 'material_category',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='material.materialcategory', verbose_name='分类'),
        ),
    ]
