# Generated by Django 6.0.3 on 2026-05-04 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_materialcategory_alter_material_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('remark', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '物料分类',
                'verbose_name_plural': '物料分类',
                'db_table': 'material_category',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(blank=True, choices=[('cable', '线缆类'), ('network', '网络设备'), ('server', '服务器/存储'), ('cabinet', '机柜/配件'), ('monitor', '监控设备'), ('access', '门禁设备'), ('software', '软件/许可'), ('tool', '工具/耗材')], db_column='category', default='', max_length=20, verbose_name='分类'),
        ),
        migrations.CreateModel(
            name='MaterialBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='BOM名称')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='版本号')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否当前版本')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_boms', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('material', models.ForeignKey(help_text='选择要建立BOM结构的物料', on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='material.material', verbose_name='主物料')),
            ],
            options={
                'verbose_name': '物料BOM',
                'verbose_name_plural': '物料BOM清单',
                'db_table': 'material_bom',
                'ordering': ['-created_at'],
                'unique_together': {('material', 'version')},
            },
        ),
        migrations.CreateModel(
            name='MaterialBOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=12, verbose_name='数量')),
                ('unit', models.CharField(default='个', max_length=20, verbose_name='单位')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='排序序号')),
                ('remark', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='material.materialbom', verbose_name='所属BOM')),
                ('child_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_boms', to='material.material', verbose_name='子件物料')),
            ],
            options={
                'verbose_name': 'BOM子件',
                'verbose_name_plural': 'BOM子件明细',
                'db_table': 'material_bom_item',
                'ordering': ['sequence', 'id'],
            },
        ),
    ]
