# Generated by Django 5.2.13 on 2026-05-04 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_add_bom_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialBOMNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=12, verbose_name='数量')),
                ('unit', models.CharField(default='个', max_length=20, verbose_name='单位')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='排序序号')),
                ('remark', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='material.materialbom', verbose_name='所属BOM')),
                ('child_bom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_nodes_as_child', to='material.materialbom', verbose_name='子件BOM')),
                ('child_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_nodes_as_child', to='material.material', verbose_name='子件物料')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='material.materialbomnode', verbose_name='父节点')),
            ],
            options={
                'verbose_name': 'BOM节点',
                'verbose_name_plural': 'BOM节点',
                'db_table': 'material_bom_node',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='MaterialBOMItem',
        ),
    ]
