# Generated by Django 5.2.13 on 2026-05-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_remove_bom_add_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='company_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='materialbom',
            name='company_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='materialbomnode',
            name='company_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='materialcategory',
            name='company_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='materialusagelog',
            name='company_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='所属公司'),
        ),
    ]
