# Generated by Django 5.2.14 on 2026-06-02 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_drop_client_extra_fields'),
        ('material', '0005_add_company_id_to_equipment_material'),
        ('tasks', '0010_allow_null_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialInboundLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='入库数量')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='本次入库的单价，用于计算加权平均成本', max_digits=12, null=True, verbose_name='入库单价')),
                ('inbound_date', models.DateField(auto_now_add=True, verbose_name='入库日期')),
                ('source_type', models.CharField(blank=True, default='purchase', help_text='purchase/bom/transfer/adjustment', max_length=20, verbose_name='入库来源')),
                ('company_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='所属公司')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_inbound_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_logs', to='material.material', verbose_name='物料')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_inbound_logs', to='tasks.project', verbose_name='入库项目')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_inbound_logs', to='crm.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '物料入库记录',
                'verbose_name_plural': '物料入库记录',
                'db_table': 'material_inbound_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
