# Generated by Django 5.2.14 on 2026-06-02 00:56

from django.db import migrations, models


def copy_stock_to_init_stock(apps, schema_editor):
    """复制现有 stock 值到 init_stock"""
    Material = apps.get_model('material', 'Material')
    for obj in Material.objects.all():
        obj.init_stock = obj.stock or 0
        obj.save(update_fields=['init_stock'])


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_add_material_inbound_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='init_stock',
            field=models.PositiveIntegerField(default=0, help_text='启用库存流水前的初始库存数量', verbose_name='期初库存'),
        ),
        migrations.RunPython(copy_stock_to_init_stock, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='material',
            name='stock',
        ),
    ]
