# Generated by Django 5.2.13 on 2026-04-20 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('notification_type', models.CharField(choices=[('system', '系统通知'), ('task', '任务通知'), ('approval', '审批通知'), ('wage', '工资通知'), ('project', '项目通知')], default='system', max_length=20, verbose_name='类型')),
                ('level', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('success', '成功')], default='info', max_length=20, verbose_name='级别')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('related_id', models.IntegerField(blank=True, null=True, verbose_name='关联ID')),
                ('related_type', models.CharField(blank=True, default='', max_length=50, verbose_name='关联类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'core_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
