# Generated by Django 5.2.13 on 2026-04-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='category',
            field=models.CharField(choices=[('项目', '项目'), ('任务', '任务'), ('财务', '财务'), ('审批', '审批'), ('系统', '系统'), ('客户', '客户'), ('合同', '合同'), ('文件', '文件'), ('工资', '工资'), ('其他', '其他')], default='其他', max_length=20, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(blank=True, choices=[('read', '读取'), ('write', '写入'), ('delete', '删除'), ('admin', '管理')], default='read', max_length=20, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='resource',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='资源路径'),
        ),
    ]
