# Generated by Django 5.2.13 on 2026-04-24 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_menu_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.role', verbose_name='角色(FK)'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='menu_code',
            field=models.CharField(blank=True, default='', help_text='关联的菜单编码，如 project.list, task.create, expense.delete', max_length=50, verbose_name='菜单编码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', '管理员'), ('pm', '项目经理'), ('dev', '开发人员'), ('business', '商务人员'), ('viewer', '访客')], default='dev', max_length=20, verbose_name='角色'),
        ),
    ]
