# Generated by Django 5.2.13 on 2026-04-24 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_role_fk_alter_permission_menu_code_and_more'),
    ]

    operations = [
        # 1. Add granted_by FK to core_role_permission (nullable for existing rows)
        migrations.AddField(
            model_name='rolepermission',
            name='granted_by',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=models.SET_NULL,
                related_name='granted_roles',
                to='core.user',
                verbose_name='授权人',
            ),
        ),
        # 2. Rename created_at to granted_at (keep created_at data as granted_at for existing rows)
        migrations.AddField(
            model_name='rolepermission',
            name='granted_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name='授权时间',
            ),
            preserve_default=False,
        ),
        # 3. Remove the old permission_type field from core_role_permission
        migrations.RemoveField(
            model_name='rolepermission',
            name='permission_type',
        ),
        # 4. Create the audit log table
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(
                    choices=[
                        ('assign_role', '分配角色'),
                        ('remove_role', '移除角色'),
                        ('grant_permission', '授予权限'),
                        ('revoke_permission', '撤销权限'),
                    ],
                    max_length=20, verbose_name='操作类型',
                )),
                ('ip_address', models.GenericIPAddressField(
                    blank=True, null=True, verbose_name='IP地址',
                )),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('details', models.TextField(blank=True, verbose_name='变更详情')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='操作时间',
                )),
                ('user', models.ForeignKey(
                    null=True, on_delete=models.SET_NULL,
                    related_name='permission_logs',
                    to='core.user', verbose_name='操作用户',
                )),
                ('target_user', models.ForeignKey(
                    null=True, on_delete=models.SET_NULL,
                    related_name='+', to='core.user', verbose_name='目标用户',
                )),
                ('role', models.ForeignKey(
                    blank=True, null=True, on_delete=models.SET_NULL,
                    to='core.role', verbose_name='角色',
                )),
                ('permission', models.ForeignKey(
                    blank=True, null=True, on_delete=models.SET_NULL,
                    to='core.permission', verbose_name='权限',
                )),
            ],
            options={
                'db_table': 'core_permission_audit_log',
                'ordering': ['-created_at'],
                'verbose_name': '权限审计日志',
                'verbose_name_plural': '权限审计日志',
            },
        ),
    ]
