# Generated by Django 5.2.13 on 2026-04-25 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fix_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolepermission',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role_fk',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='expires_at',
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
                ('status', models.CharField(choices=[('success', '登录成功'), ('failed', '登录失败')], max_length=20, verbose_name='登录状态')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('fail_reason', models.CharField(blank=True, default='', max_length=200, verbose_name='失败原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'db_table': 'core_login_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['username', '-created_at'], name='core_login__usernam_5c8926_idx'), models.Index(fields=['-created_at'], name='core_login__created_e27a3f_idx')],
            },
        ),
    ]
