# Generated by Django 5.2.13 on 2026-04-25 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_login_log'),
        ('finance', '0010_add_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='finance.company', verbose_name='所属公司'),
        ),
    ]
