# Generated by Django 5.2.13 on 2026-04-25 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_user_company'),
        ('finance', '0011_multi_company_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='finance.company', verbose_name='所属公司（兼容字段）'),
        ),
        migrations.CreateModel(
            name='UserCompanyRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', '公司管理员'), ('staff', '普通员工')], default='staff', max_length=20, verbose_name='角色')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='finance.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户公司角色',
                'verbose_name_plural': '用户公司角色',
                'db_table': 'core_user_company_role',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
