# Generated by Django 5.2.13 on 2026-04-26 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_company_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('approval_auto_enabled', 'approval_auto_enabled'), ('approval_timeout_hours', 'approval_timeout_hours'), ('approval_escalate_enabled', 'approval_escalate_enabled'), ('wage_submit_creates_approval', 'wage_submit_creates_approval'), ('multi_level_approval_enabled', 'multi_level_approval_enabled')], max_length=100, unique=True, verbose_name='设置键')),
                ('value', models.CharField(max_length=500, verbose_name='设置值')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='说明')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '系统设置',
                'db_table': 'core_system_setting',
            },
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='OperationAuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=150, verbose_name='操作用户')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('app_label', models.CharField(db_index=True, max_length=50, verbose_name='应用')),
                ('model_name', models.CharField(db_index=True, max_length=100, verbose_name='模型')),
                ('object_id', models.PositiveIntegerField(db_index=True, null=True, verbose_name='对象ID')),
                ('object_repr', models.CharField(blank=True, max_length=500, verbose_name='对象摘要')),
                ('action', models.CharField(choices=[('create', '新增'), ('update', '修改'), ('delete', '删除')], max_length=10, verbose_name='操作类型')),
                ('changes', models.TextField(blank=True, verbose_name='变更内容')),
                ('approval_flow_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='关联审批流')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '操作审计日志',
                'verbose_name_plural': '操作审计日志',
                'db_table': 'core_operation_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['app_label', 'model_name', '-created_at'], name='core_operat_app_lab_525182_idx'), models.Index(fields=['user', '-created_at'], name='core_operat_user_id_8338c7_idx'), models.Index(fields=['-created_at'], name='core_operat_created_ce153c_idx'), models.Index(fields=['approval_flow_id', '-created_at'], name='core_operat_approva_931190_idx')],
            },
        ),
    ]
