# Generated by Django 4.2.30 on 2026-05-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_system_setting_external_configs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='key',
            field=models.CharField(choices=[('approval_auto_enabled', 'approval_auto_enabled'), ('approval_timeout_hours', 'approval_timeout_hours'), ('approval_escalate_enabled', 'approval_escalate_enabled'), ('wage_submit_creates_approval', 'wage_submit_creates_approval'), ('multi_level_approval_enabled', 'multi_level_approval_enabled'), ('email_smtp_host', 'email_smtp_host'), ('email_smtp_port', 'email_smtp_port'), ('email_smtp_user', 'email_smtp_user'), ('email_smtp_password', 'email_smtp_password'), ('email_use_tls', 'email_use_tls'), ('email_from', 'email_from'), ('site_domain', 'site_domain'), ('site_https_enabled', 'site_https_enabled'), ('ssl_cert_path', 'ssl_cert_path'), ('ssl_key_path', 'ssl_key_path'), ('ssl_auto_renew', 'ssl_auto_renew')], max_length=100, unique=True, verbose_name='设置键'),
        ),
    ]
