# Generated by Django 5.2.13 on 2026-05-06 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_auditlog_company_id'),
        ('finance', '0009_add_company_id_to_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logs', to='finance.company', verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='notification',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='finance.company', verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='permissionauditlog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.company', verbose_name='公司'),
        ),
    ]
