# Generated by Django 5.2.13 on 2026-05-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_company_id_to_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_changed',
            field=models.BooleanField(default=False, verbose_name='密码是否已修改'),
        ),
    ]
