# Generated by Django 5.2.13 on 2026-05-22 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_usercompanyrole_is_primary'),
        ('finance', '0026_alter_expense_status_alter_income_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='模块名')),
                ('label', models.CharField(max_length=100, verbose_name='显示名称')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='图标')),
                ('category', models.CharField(blank=True, default='', max_length=50, verbose_name='分类')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '模块',
                'verbose_name_plural': '模块',
                'db_table': 'core_module',
                'ordering': ['category', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ModuleAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='动作名')),
                ('label', models.CharField(max_length=100, verbose_name='显示名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('perm_codes', models.JSONField(default=list, verbose_name='对应权限码列表')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.module')),
            ],
            options={
                'verbose_name': '模块动作',
                'verbose_name_plural': '模块动作',
                'db_table': 'core_module_action',
                'unique_together': {('module', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserCompanyPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_granted', models.BooleanField(default=False, verbose_name='是否授权')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.moduleaction')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='finance.company')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户公司权限',
                'verbose_name_plural': '用户公司权限',
                'db_table': 'core_user_company_permission',
                'unique_together': {('user', 'company', 'module', 'action')},
            },
        ),
    ]
