# Generated by Django 6.0.3 on 2026-05-24 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_permission_matrix_phase1'),
        ('finance', '0026_alter_expense_status_alter_income_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercompanyrole',
            name='role',
        ),
        migrations.AddField(
            model_name='usercompanypermission',
            name='source',
            field=models.CharField(default='manual', help_text='manual=手动授予，role:ID=由CompanyRole.ID=ID批量分配', max_length=50, verbose_name='权限来源'),
        ),
        migrations.CreateModel(
            name='CompanyRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='角色名称')),
                ('code', models.CharField(max_length=50, verbose_name='角色代码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_roles', to='finance.company', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '公司角色',
                'verbose_name_plural': '公司角色',
                'db_table': 'core_company_role',
            },
        ),
        migrations.AddField(
            model_name='usercompanyrole',
            name='company_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_assignments', to='core.companyrole', verbose_name='公司角色'),
        ),
        migrations.CreateModel(
            name='CompanyRolePermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('company_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companyrole')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permission')),
            ],
            options={
                'verbose_name': '公司角色权限',
                'verbose_name_plural': '公司角色权限',
                'db_table': 'core_company_role_permission',
                'unique_together': {('company_role', 'permission')},
            },
        ),
        migrations.AddField(
            model_name='companyrole',
            name='permissions',
            field=models.ManyToManyField(related_name='company_roles', through='core.CompanyRolePermission', to='core.permission', verbose_name='权限集合'),
        ),
        migrations.AlterUniqueTogether(
            name='companyrole',
            unique_together={('company', 'code')},
        ),
    ]
