# Generated by Django 5.2.13 on 2026-05-29 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_permission_unique_together_and_more'),
        ('finance', '0041_alter_account_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrole',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_roles', to='finance.company', verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='companyrolepermission',
            name='company_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_permissions', to='core.companyrole', verbose_name='公司角色'),
        ),
        migrations.AlterField(
            model_name='companyrolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='core.permission', verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='usercompanypermission',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.moduleaction'),
        ),
        migrations.AlterField(
            model_name='usercompanypermission',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_permissions', to='finance.company'),
        ),
        migrations.AlterField(
            model_name='usercompanypermission',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.module'),
        ),
        migrations.AlterField(
            model_name='usercompanypermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercompanyrole',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_roles', to='finance.company'),
        ),
        migrations.AlterField(
            model_name='usercompanyrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermodulepermission',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='module_permissions', to='finance.company'),
        ),
        migrations.AlterField(
            model_name='usermodulepermission',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_permissions', to='core.module'),
        ),
        migrations.AlterField(
            model_name='usermodulepermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='module_permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
