# Generated by Django 5.2.14 on 2026-06-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_companyrole_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('material', '物料'), ('client', '客户'), ('supplier', '供应商'), ('employee', '员工'), ('equipment', '设备')], max_length=50, unique=True, verbose_name='模块')),
                ('prefix', models.CharField(default='', help_text='如 WL-, KH-, GYS-, YG-, SB-', max_length=20, verbose_name='前缀')),
                ('include_year', models.BooleanField(default=False, help_text='编号中加入年份', verbose_name='包含年份')),
                ('year_format', models.CharField(default='%Y', help_text='%Y=四位数, %y=两位数', max_length=10, verbose_name='年份格式')),
                ('digit_count', models.PositiveIntegerField(default=4, help_text='如4位=0001', verbose_name='流水号位数')),
                ('separator', models.CharField(default='-', max_length=5, verbose_name='分隔符')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='说明')),
                ('company_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='所属公司')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '编码规则',
                'verbose_name_plural': '编码规则',
                'db_table': 'core_coding_rule',
            },
        ),
    ]
