# Generated by Django 5.2.14 on 2026-06-02 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_coding_rule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyRole',
        ),
        migrations.DeleteModel(
            name='CompanyRolePermission',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='UserCompanyPermission',
        ),
        migrations.DeleteModel(
            name='UserCompanyRole',
        ),
    ]
