# Generated by Django 4.2.18 on 2026-04-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='审批名称')),
                ('flow_type', models.CharField(choices=[('payment', '付款审批'), ('project', '立项审批'), ('expense', '支出审批'), ('wage', '工资审批'), ('custom', '自定义审批')], max_length=20, verbose_name='审批类型')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='审批涉及的金额', max_digits=14, null=True, verbose_name='金额')),
                ('description', models.TextField(blank=True, default='', verbose_name='审批说明')),
                ('current_node_order', models.IntegerField(default=0, verbose_name='当前节点顺序')),
                ('result_comment', models.TextField(blank=True, default='', verbose_name='审批结论')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='审批完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '审批流',
                'verbose_name_plural': '审批流',
                'db_table': 'approvals_flow',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_order', models.IntegerField(default=1, verbose_name='审批顺序')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('skipped', '已跳过')], default='pending', max_length=20, verbose_name='状态')),
                ('comment', models.TextField(blank=True, default='', verbose_name='审批意见')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
            ],
            options={
                'verbose_name': '审批节点',
                'verbose_name_plural': '审批节点',
                'db_table': 'approvals_node',
                'ordering': ['node_order'],
            },
        ),
    ]
