# Generated by Django 5.2.13 on 2026-04-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalflow',
            name='flow_type',
            field=models.CharField(choices=[('payment', '付款审批'), ('project', '立项审批'), ('expense', '支出审批'), ('income', '收入确认'), ('wage', '工资审批'), ('custom', '自定义审批')], max_length=20, verbose_name='审批类型'),
        ),
    ]
