# Generated by Django 5.2.13 on 2026-04-23 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_alter_approvalflow_flow_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalnode',
            name='delegated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_nodes', to=settings.AUTH_USER_MODEL, verbose_name='委托给'),
        ),
        migrations.AddField(
            model_name='approvalnode',
            name='node_type',
            field=models.CharField(choices=[('approver', '审批人'), ('delegate', '委托'), ('transfer', '转交')], default='approver', help_text='标识节点是审批人还是转交/委托产生的节点', max_length=20, verbose_name='节点类型'),
        ),
    ]
