# Generated by Django 5.2.13 on 2026-04-24 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0004_add_node_type_and_delegated_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='模板名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='模板编码')),
                ('flow_type', models.CharField(choices=[('payment', '付款审批'), ('project', '立项审批'), ('expense', '支出审批'), ('income', '收入确认'), ('wage', '工资审批'), ('custom', '自定义审批')], max_length=20, verbose_name='审批类型')),
                ('description', models.TextField(blank=True, default='', verbose_name='模板说明')),
                ('nodes', models.JSONField(default=list, help_text='节点配置JSON数组，每个节点包含：node_order(顺序)/approver_type(admin/department_head/specific_user)/approver_id(用户ID)/timeout_hours(超时小时)/node_type(single/all_sign)', verbose_name='节点配置')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='触发条件JSON，如：{"min_amount": 5000, "max_amount": null}', verbose_name='触发条件')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_approval_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '审批模板',
                'verbose_name_plural': '审批模板',
                'db_table': 'approvals_template',
                'ordering': ['-created_at'],
            },
        ),
    ]
