# Generated by Django 5.2.13 on 2026-04-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0005_approvaltemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalnode',
            name='timeout_hours',
            field=models.IntegerField(blank=True, help_text='节点超时时间（小时），超时后自动过期', null=True, verbose_name='超时小时数'),
        ),
    ]
