# Generated by Django 5.2.13 on 2026-04-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0006_add_timeout_hours_to_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalflow',
            name='related_id',
            field=models.IntegerField(default=0, help_text='关联业务对象的ID', verbose_name='关联业务ID'),
        ),
        migrations.AddField(
            model_name='approvalflow',
            name='related_type',
            field=models.CharField(default='', help_text='关联业务对象类型，如 expense/income/contract/project', max_length=50, verbose_name='关联业务类型'),
        ),
        migrations.AlterField(
            model_name='approvalnode',
            name='status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('skipped', '已跳过'), ('expired', '已过期')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
