# Generated by Django 5.2.13 on 2026-04-29 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0007_add_related_type_and_id'),
        ('finance', '0013_fix_wagerecord_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalflow',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_flows', to='finance.company', verbose_name='所属公司'),
        ),
    ]
