# Generated by Django 5.2.13 on 2026-05-02 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0008_add_company_to_approvalflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalflow',
            name='company',
        ),
    ]
