# Generated by Django 5.2.13 on 2026-04-23 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_add_supplier_and_client_code_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='industry',
        ),
        migrations.AddField(
            model_name='client',
            name='category',
            field=models.CharField(blank=True, choices=[('enterprise', '企业客户'), ('government', '政府事业单位'), ('special', '特殊客户')], default='', max_length=20, verbose_name='客户分类'),
        ),
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='客户编码'),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='供应商编码')),
                ('name', models.CharField(max_length=200, verbose_name='供应商名称')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('brands', models.CharField(blank=True, default='', help_text='多个品牌用逗号分隔', max_length=500, verbose_name='代理品牌')),
                ('status', models.CharField(choices=[('active', '合作中'), ('inactive', '已停止')], default='active', max_length=20, verbose_name='合作状态')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='地址')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_suppliers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'db_table': 'crm_supplier',
                'ordering': ['-created_at'],
            },
        ),
    ]
