# Generated by Django 5.2.13 on 2026-04-28 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_client_industry_client_category_client_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='counterparty_type',
            field=models.CharField(choices=[('client', '客户'), ('supplier', '供应商')], default='client', max_length=20, verbose_name='对方类型'),
        ),
        migrations.AddField(
            model_name='contract',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='crm.supplier', verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='crm.client', verbose_name='客户'),
        ),
    ]
