# Generated by Django 5.2.13 on 2026-05-02 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_add_contract_counterparty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='来源名称')),
                ('remark', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '客户来源',
                'verbose_name_plural': '客户来源',
                'db_table': 'crm_client_source',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='contracts/%Y%m/', verbose_name='合同附件'),
        ),
        migrations.AddField(
            model_name='client',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='crm.clientsource', verbose_name='客户来源'),
        ),
    ]
