# Generated by Django 5.2.13 on 2026-05-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_contract_fix_missing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='商机名称')),
                ('stage', models.CharField(choices=[('lead', '线索'), ('qualify', '意向'), ('proposal', '方案'), ('negotiation', '商务'), ('won', '成交'), ('lost', '失败')], default='lead', max_length=20, verbose_name='销售阶段')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=20, verbose_name='优先级')),
                ('expected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='预计金额')),
                ('probability', models.IntegerField(default=10, help_text='0-100', verbose_name='赢单概率%')),
                ('estimated_close_date', models.DateField(blank=True, null=True, verbose_name='预计成交日期')),
                ('actual_close_date', models.DateField(blank=True, null=True, verbose_name='实际成交日期')),
                ('product_lines', models.CharField(blank=True, default='', help_text='逗号分隔', max_length=500, verbose_name='产品线')),
                ('competitor', models.CharField(blank=True, default='', max_length=300, verbose_name='竞争对手')),
                ('lost_reason', models.TextField(blank=True, default='', verbose_name='失败原因')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='crm.client', verbose_name='客户')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='crm.contact', verbose_name='联系人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opportunities', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='finance.company', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '商机',
                'verbose_name_plural': '商机',
                'db_table': 'crm_opportunity',
                'ordering': ['-created_at'],
            },
        ),
    ]
