# Generated by Django 5.2.13 on 2026-05-06 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_add_opportunity'),
        ('finance', '0014_company_bank_account_company_bank_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='approval_flow',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='signed_date',
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='finance.company', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='contract',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='finance.company', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='contractchangelog',
            name='company_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='company_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='finance.company', verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='clientsource',
            name='name',
            field=models.CharField(max_length=100, verbose_name='来源名称'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_status',
            field=models.CharField(choices=[('pending', '待收款'), ('partial', '部分收款'), ('paid', '已收款')], default='pending', max_length=20, verbose_name='付款状态'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='已收款'),
        ),
        migrations.AlterField(
            model_name='followuprecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_followups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followuprecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='contractchangelog',
            table='crm_contract_change_log',
        ),
        migrations.AlterModelTable(
            name='paymentplan',
            table='crm_payment_plan',
        ),
    ]
