# Generated by Django 5.2.13 on 2026-05-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_add_company_id_to_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bank_account',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='银行账号'),
        ),
        migrations.AddField(
            model_name='client',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='开户行'),
        ),
        migrations.AddField(
            model_name='client',
            name='counterparty_type',
            field=models.CharField(blank=True, choices=[('enterprise', '企业'), ('individual', '个人'), ('government', '政府/事业单位')], default='enterprise', max_length=20, verbose_name='对方类型'),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_id',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='纳税人识别号'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_account',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='银行账号'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='开户行'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='counterparty_type',
            field=models.CharField(blank=True, choices=[('enterprise', '企业'), ('individual', '个人'), ('government', '政府/事业单位')], default='enterprise', max_length=20, verbose_name='对方类型'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_id',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='纳税人识别号'),
        ),
        migrations.AlterField(
            model_name='client',
            name='category',
            field=models.CharField(blank=True, choices=[('enterprise', '企业客户'), ('government', '政府事业单位'), ('individual', '个人客户'), ('special', '特殊客户')], default='', max_length=20, verbose_name='客户分类'),
        ),
    ]
