# Generated by Django 5.2.13 on 2026-05-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_add_tax_bank_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bank_addr',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='支行地址'),
        ),
        migrations.AddField(
            model_name='client',
            name='bank_branch',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='开户行支行'),
        ),
        migrations.AddField(
            model_name='client',
            name='bank_code',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='支行联行号'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_addr',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='支行地址'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_branch',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='开户行支行'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_code',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='支行联行号'),
        ),
    ]
