# Generated by Django 5.2.13 on 2026-06-02
# 为Opportunity增加contract外键（商机→合同转化）

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_drop_client_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='contract',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='opportunities',
                to='crm.contract',
                verbose_name='关联合同',
            ),
        ),
    ]
