# Generated by Django 5.2.13 on 2026-06-02
# ContractMilestone 合同里程碑模型

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_opportunity_add_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='里程碑名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('plan_date', models.DateField(verbose_name='计划完成日期')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='实际完成日期')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='该里程碑对应的收款/付款金额', max_digits=15, verbose_name='里程碑金额')),
                ('status', models.CharField(
                    choices=[('pending', '待开始'), ('in_progress', '进行中'), ('completed', '已完成'), ('delayed', '已延期')],
                    default='pending', max_length=20, verbose_name='状态')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='milestones',
                    to='crm.contract', verbose_name='关联合同')),
            ],
            options={
                'verbose_name': '合同里程碑',
                'verbose_name_plural': '合同里程碑',
                'db_table': 'crm_contract_milestone',
                'ordering': ['sort_order', 'plan_date'],
            },
        ),
    ]
