# Generated by Django 6.0.3 on 2026-06-02 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_contractmilestone'),
        ('tasks', '0010_allow_null_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='tasks.project', verbose_name='关联项目'),
        ),
    ]
