# Generated by Django 5.2.13 on 2026-04-29 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0013_fix_wagerecord_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelPlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('feishu', '飞书'), ('wecom', '企业微信'), ('wechat', '微信个人号'), ('dingtalk', '钉钉'), ('email', '邮件'), ('sms', '短信')], max_length=20, verbose_name='渠道类型')),
                ('plugin_name', models.CharField(max_length=50, verbose_name='插件名称')),
                ('app_name', models.CharField(blank=True, max_length=100, verbose_name='应用名称')),
                ('connection_mode', models.CharField(choices=[('websocket', '长连接'), ('webhook', 'Webhook回调'), ('polling', '轮询')], default='websocket', max_length=20, verbose_name='连接模式')),
                ('pairing_mode', models.CharField(choices=[('qrcode', '二维码扫码'), ('pairing', 'DM配对'), ('manual', '手动绑定')], default='qrcode', max_length=20, verbose_name='配对模式')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='配置JSON')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_plugins', to='finance.company')),
            ],
            options={
                'verbose_name': '渠道插件',
                'verbose_name_plural': '渠道插件',
                'db_table': 'channels_plugin',
                'unique_together': {('company', 'channel_type', 'plugin_name')},
            },
        ),
        migrations.CreateModel(
            name='ChannelBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_open_id', models.CharField(max_length=128, verbose_name='平台OpenID')),
                ('platform_user_info', models.JSONField(blank=True, default=dict, verbose_name='平台用户信息')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('active', '已激活'), ('inactive', '已失效')], default='active', max_length=20, verbose_name='状态')),
                ('bound_at', models.DateTimeField(auto_now_add=True, verbose_name='绑定时间')),
                ('last_active_at', models.DateTimeField(auto_now=True, verbose_name='最后活跃')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_bindings', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='channels.channelplugin')),
            ],
            options={
                'verbose_name': '渠道绑定',
                'verbose_name_plural': '渠道绑定',
                'db_table': 'channels_binding',
                'unique_together': {('user', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('notification_type', models.CharField(max_length=50, verbose_name='通知类型')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('failed', '发送失败'), ('read', '已读')], default='pending', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('binding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='channels.channelbinding')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='channels.channelplugin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '通知日志',
                'verbose_name_plural': '通知日志',
                'db_table': 'channels_notification_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
