# Generated by Django 5.2.13 on 2026-04-29 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_add_channel_plugin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='操作IP')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent')),
                ('action', models.CharField(choices=[('channel_create', '创建渠道'), ('channel_update', '更新渠道配置'), ('channel_delete', '删除渠道'), ('channel_validate', '验证凭证'), ('channel_enable', '启用渠道'), ('channel_disable', '禁用渠道'), ('bind_create', '创建绑定'), ('bind_delete', '解除绑定'), ('oauth_callback_success', 'OAuth回调成功'), ('oauth_callback_fail', 'OAuth回调失败'), ('webhook_received', '接收Webhook事件'), ('test_message_sent', '发送测试消息'), ('notification_sent', '发送通知')], db_index=True, max_length=32, verbose_name='操作类型')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='操作详情')),
                ('result', models.CharField(choices=[('success', '成功'), ('failure', '失败'), ('pending', '待定')], db_index=True, default='success', max_length=16, verbose_name='操作结果')),
                ('error_message', models.CharField(blank=True, max_length=512, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间')),
                ('binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='channels.channelbinding', verbose_name='关联绑定')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='channels.channelplugin', verbose_name='关联渠道')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '渠道审计日志',
                'verbose_name_plural': '渠道审计日志',
                'db_table': 'channels_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', 'created_at'], name='channels_au_channel_7e9de7_idx'), models.Index(fields=['user', 'created_at'], name='channels_au_user_id_11a644_idx'), models.Index(fields=['action', 'created_at'], name='channels_au_action_25fe43_idx')],
            },
        ),
    ]
