# Generated by Django 5.2.13 on 2026-05-22 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_fix_channel_unique_constraint'),
        ('finance', '0026_alter_expense_status_alter_income_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRouterRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50, verbose_name='事件类型')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '普通'), ('important', '重要'), ('critical', '紧急')], default='normal', max_length=20, verbose_name='优先级')),
                ('channel_type', models.CharField(max_length=20, verbose_name='渠道类型')),
                ('recipient_scope', models.CharField(default='all', max_length=50, verbose_name='接收人范围')),
                ('custom_user_ids', models.TextField(blank=True, verbose_name='自定义用户ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='finance.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '通知路由规则',
                'verbose_name_plural': '通知路由规则',
                'db_table': 'channels_notification_router_rule',
                'ordering': ['-created_at'],
            },
        ),
    ]
