# Generated by Django 5.2.13 on 2026-05-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_add_notification_router_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelplugin',
            name='usage',
            field=models.CharField(choices=[('broadcast', '群通知'), ('personal', '私信通知')], default='personal', max_length=20, verbose_name='用途'),
        ),
    ]
