# Generated by Django 5.2.13 on 2026-05-28 08:22

from django.db import migrations
import json


def migrate_usage(apps, schema_editor):
    ChannelPlugin = apps.get_model('channels', 'ChannelPlugin')
    for ch in ChannelPlugin.objects.all():
        config = ch.config or {}
        has_webhook = bool(config.get('webhook_url'))
        has_app_id = bool(config.get('app_id') or config.get('app_key'))
        
        if has_webhook and not has_app_id:
            ch.usage = 'broadcast'
        elif has_app_id:
            ch.usage = 'personal'
        elif has_webhook:
            ch.usage = 'broadcast'
        else:
            ch.usage = 'personal'
        ch.save(update_fields=['usage'])


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_channelplugin_usage'),
    ]

    operations = [
        migrations.RunPython(migrate_usage, migrations.RunPython.noop),
    ]
