# Generated by Django 5.2.13 on 2026-04-20 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0003_add_status_and_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='files.filecategory', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '文件分类',
                'verbose_name_plural': '文件分类',
                'db_table': 'file_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='company_files/%Y/%m/', verbose_name='文件')),
                ('file_name', models.CharField(max_length=300, verbose_name='文件名')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='finance.company', verbose_name='公司')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='files.filecategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '公司文件',
                'verbose_name_plural': '公司文件',
                'db_table': 'company_file',
                'ordering': ['-created_at'],
            },
        ),
    ]
