# Generated by Django 5.2.13 on 2026-04-23 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('tasks', '0002_add_task_flow_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfile',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_files', to='tasks.project', verbose_name='关联项目'),
        ),
    ]
