# Generated by Hermes Agent
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = False

    dependencies = [
        ('files', '0002_add_project_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfile',
            name='is_current',
            field=models.BooleanField(default=True, verbose_name='当前版本'),
        ),
        migrations.AddField(
            model_name='companyfile',
            name='previous_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='files.companyfile', verbose_name='上一版本'),
        ),
        migrations.AddField(
            model_name='companyfile',
            name='version',
            field=models.IntegerField(default=1, verbose_name='版本号'),
        ),
        migrations.AddIndex(
            model_name='companyfile',
            index=models.Index(fields=['company', 'category', 'file_name'], name='file_cmc_idx'),
        ),
    ]
