# Generated by Django 5.2.13 on 2026-05-02 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_clientsource_contract_attachment_client_source'),
        ('files', '0003_add_version_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfile',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='crm.contract', verbose_name='关联合同'),
        ),
    ]
