# Generated by Django 6.0.3 on 2026-05-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_companyfile_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfile',
            name='alias',
            field=models.CharField(blank=True, default='', help_text='用户自定义的文件别名，方便搜索识别', max_length=300, verbose_name='别名'),
        ),
    ]
