# Generated by Django 5.2.14 on 2026-06-03 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_add_alias_field'),
        ('finance', '0045_add_expense_amortization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='finance.company', verbose_name='公司'),
        ),
    ]
