# Generated by Django 5.2.13 on 2026-04-29 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0013_fix_wagerecord_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('feishu', '飞书'), ('wecom', '企业微信'), ('qq', 'QQ 机器人'), ('telegram', 'Telegram'), ('email', '邮件')], max_length=20, verbose_name='渠道类型')),
                ('app_name', models.CharField(help_text='显示在用户端的机器人名称，如"工程管理系统通知小助手"', max_length=100, verbose_name='应用名称')),
                ('app_id', models.CharField(blank=True, help_text='飞书 CLI_xxx / 企微 CorpID / QQ AppID', max_length=100, verbose_name='App ID / Client ID')),
                ('app_secret', models.CharField(blank=True, help_text='凭证敏感字段，页面不展示明文', max_length=200, verbose_name='App Secret / Client Secret')),
                ('webhook_url', models.URLField(blank=True, help_text='仅 Webhook 模式需要', verbose_name='Webhook 地址')),
                ('webhook_token', models.CharField(blank=True, max_length=200, verbose_name='Webhook 验证令牌')),
                ('connection_mode', models.CharField(choices=[('websocket', 'WebSocket 长连接'), ('webhook', 'Webhook 回调')], default='websocket', max_length=20, verbose_name='连接模式')),
                ('pairing_mode', models.CharField(choices=[('pairing', '配对模式（用户扫码+发消息自动绑定）'), ('allowlist', '白名单模式（手动添加用户 open_id）')], default='pairing', max_length=20, verbose_name='配对模式')),
                ('allow_from', models.TextField(blank=True, help_text='配对模式下可留空；白名单模式下填入允许的 open_id，逗号分隔', verbose_name='白名单 open_id')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('binding_count', models.PositiveIntegerField(default=0, verbose_name='已绑定用户数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_apps', to='finance.company', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '通知应用',
                'verbose_name_plural': '通知应用',
                'db_table': 'notify_app',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'channel_type', 'app_name')},
            },
        ),
        migrations.CreateModel(
            name='NotifyBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_open_id', models.CharField(help_text='飞书 open_id / 企微 userid / QQ 号 / Telegram user_id', max_length=100, verbose_name='平台 Open ID')),
                ('platform_display_name', models.CharField(blank=True, help_text='绑定时获取的用户昵称', max_length=200, verbose_name='平台显示名')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('notify_contract', models.BooleanField(default=True, verbose_name='合同通知')),
                ('notify_equipment', models.BooleanField(default=True, verbose_name='设备通知')),
                ('notify_project', models.BooleanField(default=True, verbose_name='项目通知')),
                ('notify_approval', models.BooleanField(default=True, verbose_name='审批通知')),
                ('notify_wage', models.BooleanField(default=True, verbose_name='工资通知')),
                ('bound_at', models.DateTimeField(auto_now_add=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='最后通知时间')),
                ('notify_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='notifications.notifyapp', verbose_name='通知应用')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_bindings', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '通知绑定',
                'verbose_name_plural': '通知绑定',
                'db_table': 'notify_binding',
                'ordering': ['-bound_at'],
                'unique_together': {('user', 'notify_app')},
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='通知标题')),
                ('content', models.TextField(blank=True, verbose_name='通知内容')),
                ('notify_type', models.CharField(help_text='contract/equipment/project/approval/wage/system', max_length=30, verbose_name='通知类型')),
                ('related_id', models.IntegerField(blank=True, null=True, verbose_name='关联记录ID')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('failed', '发送失败'), ('read', '已读')], default='pending', max_length=20, verbose_name='发送状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notifybinding', verbose_name='绑定记录')),
            ],
            options={
                'verbose_name': '通知日志',
                'verbose_name_plural': '通知日志',
                'db_table': 'notify_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
