# Generated by Django 5.2.13 on 2026-05-02 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # notifications模块不引用finance表，无需依赖
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='渠道名称')),
                ('channel_type', models.CharField(choices=[('feishu', '飞书'), ('wecom', '企业微信'), ('dingtalk', '钉钉'), ('email', '邮件'), ('webhook', '自定义Webhook')], max_length=20, verbose_name='渠道类型')),
                ('webhook_url', models.URLField(max_length=500, verbose_name='Webhook地址')),
                ('secret', models.CharField(blank=True, default='', max_length=200, verbose_name='Secret密钥')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(blank=True, help_text='关联公司；系统超级管理员可见所有渠道', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to='finance.company', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '通知渠道',
                'verbose_name_plural': '通知渠道',
                'db_table': 'notifications_channel',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotifyBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('feishu', '飞书'), ('wecom', '企业微信'), ('dingtalk', '钉钉'), ('email', '邮件')], max_length=20, verbose_name='平台')),
                ('platform_open_id', models.CharField(max_length=200, verbose_name='平台OpenID/账号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('receive_all', models.BooleanField(default=True, verbose_name='接收全部通知')),
                ('bound_at', models.DateTimeField(auto_now_add=True, verbose_name='绑定时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='notifications.notificationchannel', verbose_name='渠道')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_bindings', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户通知绑定',
                'verbose_name_plural': '用户通知绑定',
                'db_table': 'notifications_binding',
                'ordering': ['-bound_at'],
                'unique_together': {('user', 'channel', 'platform_open_id')},
            },
        ),
    ]
