# Generated by Django 4.2.30 on 2026-05-05 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_company_bank_account_company_bank_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifybinding',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后通知时间'),
        ),
        migrations.AddField(
            model_name='notifybinding',
            name='notify_approval',
            field=models.BooleanField(default=True, verbose_name='审批通知'),
        ),
        migrations.AddField(
            model_name='notifybinding',
            name='notify_contract',
            field=models.BooleanField(default=True, verbose_name='合同通知'),
        ),
        migrations.AddField(
            model_name='notifybinding',
            name='notify_equipment',
            field=models.BooleanField(default=True, verbose_name='设备通知'),
        ),
        migrations.AddField(
            model_name='notifybinding',
            name='notify_project',
            field=models.BooleanField(default=True, verbose_name='项目通知'),
        ),
        migrations.AddField(
            model_name='notifybinding',
            name='notify_wage',
            field=models.BooleanField(default=True, verbose_name='工资通知'),
        ),
        migrations.AddField(
            model_name='notifybinding',
            name='platform_display_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='平台显示名'),
        ),
        migrations.AlterField(
            model_name='notifybinding',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bindings', to='notifications.notificationchannel', verbose_name='推送渠道'),
        ),
        migrations.AlterField(
            model_name='notifybinding',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
        migrations.AlterField(
            model_name='notifybinding',
            name='platform',
            field=models.CharField(choices=[('feishu', '飞书'), ('wecom', '企业微信'), ('dingtalk', '钉钉'), ('email', '邮件')], default='feishu', max_length=20, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='notifybinding',
            name='platform_open_id',
            field=models.CharField(max_length=100, verbose_name='平台 Open ID'),
        ),
        migrations.AlterModelTable(
            name='notifybinding',
            table='notify_binding',
        ),
        migrations.CreateModel(
            name='NotifyApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('feishu', '飞书'), ('wecom', '企业微信'), ('qq', 'QQ 机器人'), ('telegram', 'Telegram'), ('email', '邮件')], max_length=20, verbose_name='渠道类型')),
                ('app_name', models.CharField(help_text='显示在用户端的机器人名称，如"工程管理系统通知小助手"', max_length=100, verbose_name='应用名称')),
                ('app_id', models.CharField(blank=True, help_text='飞书 CLI_xxx / 企微 CorpID / QQ AppID', max_length=100, verbose_name='App ID / Client ID')),
                ('app_secret', models.CharField(blank=True, help_text='凭证敏感字段，页面不展示明文', max_length=200, verbose_name='App Secret / Client Secret')),
                ('webhook_url', models.URLField(blank=True, max_length=500, verbose_name='Webhook 地址')),
                ('webhook_token', models.CharField(blank=True, max_length=200, verbose_name='Webhook 验证令牌')),
                ('connection_mode', models.CharField(choices=[('websocket', 'WebSocket 长连接'), ('webhook', 'Webhook 回调')], default='websocket', max_length=20, verbose_name='连接模式')),
                ('pairing_mode', models.CharField(choices=[('pairing', '配对模式（用户扫码+发消息自动绑定）'), ('allowlist', '白名单模式（手动添加用户 open_id）')], default='pairing', max_length=20, verbose_name='配对模式')),
                ('allow_from', models.TextField(blank=True, help_text='配对模式下可留空；白名单模式下填入允许的 open_id，逗号分隔', verbose_name='白名单 open_id')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('binding_count', models.PositiveIntegerField(default=0, verbose_name='已绑定用户数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_apps', to='finance.company', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '通知应用',
                'verbose_name_plural': '通知应用',
                'db_table': 'notify_app',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'channel_type', 'app_name')},
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='通知标题')),
                ('content', models.TextField(blank=True, verbose_name='通知内容')),
                ('notify_type', models.CharField(choices=[('contract', '合同通知'), ('equipment', '设备通知'), ('project', '项目通知'), ('approval', '审批通知'), ('wage', '工资通知'), ('system', '系统通知')], help_text='contract/equipment/project/approval/wage/system', max_length=30, verbose_name='通知类型')),
                ('related_id', models.IntegerField(blank=True, null=True, verbose_name='关联记录ID')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('failed', '发送失败'), ('read', '已读')], default='pending', max_length=20, verbose_name='发送状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notifybinding', verbose_name='绑定记录')),
            ],
            options={
                'verbose_name': '通知日志',
                'verbose_name_plural': '通知日志',
                'db_table': 'notify_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='notifybinding',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='notifybinding',
            name='notify_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notifyapp', verbose_name='通知应用'),
        ),
        migrations.AlterUniqueTogether(
            name='notifybinding',
            unique_together={('user', 'notify_app')},
        ),
    ]
