# Generated by Django 5.2.13 — multi-tenant notifications upgrade

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '__first__'),  # placeholder — real dep set bymakemigrations
    ]

    operations = [
        # 1. Add company FK to NotificationChannel (nullable for backward compat)
        migrations.AddField(
            model_name='notificationchannel',
            name='company',
            field=models.ForeignKey(
                blank=True,
                help_text='关联公司；系统超级管理员可见所有渠道',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='notification_channels',
                to='finance.company',
                verbose_name='所属公司',
            ),
        ),

        # 2. Create NotifyBinding
        migrations.CreateModel(
            name='NotifyBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(
                    choices=[('feishu', '飞书'), ('wecom', '企业微信'), ('dingtalk', '钉钉'), ('email', '邮件')],
                    max_length=20, verbose_name='平台',
                )),
                ('platform_open_id', models.CharField(max_length=200, verbose_name='平台OpenID/账号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('receive_all', models.BooleanField(default=True, verbose_name='接收全部通知')),
                ('bound_at', models.DateTimeField(auto_now_add=True, verbose_name='绑定时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('channel', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='bindings',
                    to='notifications.notificationchannel',
                    verbose_name='渠道',
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='notify_bindings',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='用户',
                )),
            ],
            options={
                'verbose_name': '用户通知绑定',
                'verbose_name_plural': '用户通知绑定',
                'db_table': 'notifications_binding',
                'ordering': ['-bound_at'],
                'unique_together': {('user', 'channel', 'platform_open_id')},
            },
        ),
    ]
