# Generated by Django 5.2.13 on 2026-05-02 06:05
# Fixed: removed duplicate AddField(channel/platform/receive_all) — now in 0003

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_company_bank_account_company_bank_name_and_more'),
        ('notifications', '0003_add_notify_binding_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifybinding',
            options={'ordering': ['-bound_at'], 'verbose_name': '用户通知绑定', 'verbose_name_plural': '用户通知绑定'},
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='company',
            field=models.ForeignKey(blank=True, help_text='关联公司；系统超级管理员可见所有渠道', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to='finance.company', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='notifybinding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        # Note: NotifyApp.company is already in 0001's CreateModel — NOT added here
        # AlterField — confirms field state (no-op from Django's perspective)
        migrations.AlterField(
            model_name='notificationlog',
            name='notify_type',
            field=models.CharField(choices=[('contract', '合同通知'), ('equipment', '设备通知'), ('project', '项目通知'), ('approval', '审批通知'), ('wage', '工资通知'), ('system', '系统通知')], help_text='contract/equipment/project/approval/wage/system', max_length=30, verbose_name='通知类型'),
        ),
        migrations.AlterField(
            model_name='notifyapp',
            name='webhook_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Webhook 地址'),
        ),
        migrations.AlterField(
            model_name='notifybinding',
            name='bound_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='绑定时间'),
        ),
        migrations.AlterField(
            model_name='notifybinding',
            name='platform_display_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='平台显示名'),
        ),
        migrations.AlterField(
            model_name='notifybinding',
            name='platform_open_id',
            field=models.CharField(max_length=100, verbose_name='平台 Open ID'),
        ),
    ]
