# Generated by Django 5.2.13 on 2026-05-17 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_allow_null_notify_app'),
        ('notifications', '0005_record_company_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifyapp',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_apps', to='finance.company', verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='notifybinding',
            name='notify_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='notifications.notifyapp', verbose_name='通知应用'),
        ),
    ]
