# Generated by Django 5.2.13 on 2026-05-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_allow_null_notify_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, help_text='事件类型，如 task_created', max_length=50)),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '普通'), ('important', '重要'), ('critical', '紧急')], default='normal', max_length=10)),
                ('channel_type', models.CharField(db_index=True, help_text='feishu/wecom/dingtalk/email', max_length=20)),
                ('recipient_scope', models.CharField(choices=[('owner', '负责人'), ('requester', '申请人'), ('all', '全部相关人'), ('custom', '自定义用户')], default='owner', max_length=20)),
                ('custom_user_ids', models.TextField(blank=True, default='', help_text='custom时用户ID列表，逗号分隔')),
                ('company_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': '通知路由',
                'verbose_name_plural': '通知路由',
                'db_table': 'notification_router',
                'ordering': ['event_type', 'priority', 'channel_type'],
            },
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='priority',
            field=models.CharField(default='normal', help_text='low / normal / important / critical', max_length=10, verbose_name='优先级'),
        ),
    ]
