# Generated by Django 5.2.13 on 2026-05-17 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_add_notification_router'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('allowed_channels', models.JSONField(blank=True, default=list, verbose_name='允许的渠道列表')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户通知偏好',
                'verbose_name_plural': '用户通知偏好',
                'db_table': 'user_notification_preference',
                'unique_together': {('user', 'event_type')},
            },
        ),
    ]
